<a href="https://colab.research.google.com/github/6230204513/data_viz_2022/blob/main/Final_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#ข้อสอบปลาย

##ก่อนเริ่ม : การเตรียมข้อมูล

###นำเข้าข้อมูล

เริ่มแรกเราจะใช้ Import pandas สำหรับใช้อ่านข้อมูลและอื่นส่วน Import os เป็นคำสั่งสำหรับอ่านค่าเพื่อให้ดึงข้อมูลมาจากไดร์ฟ

In [120]:
import pandas as pd
import os

ดึงข้อมูลโดยใช้ path เป็นตัวรองรับจาก Drive ที่ชื่อ ovrdt_data

In [121]:
from google.colab import drive
drive.mount('/content/drive')
path = '/content/drive/My Drive/ovrdt_data'

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

จากนั้นดึงข้อมูลตารางจากไฟล์ที่ชื่อ alldb.csv และ hospital_list.xlsx จากได้ drive ด้วยคำสั่่ง os.path.join และ อ่านค่าด้วย pd.read_csv พร้อมใช้ตัวแปรรองรับเป็น data_mid

In [122]:
data_file_path1 = os.path.join(path,'alldb.csv') 
alldb = pd.read_csv(data_file_path1)
alldb #ตารางแสดงการอ่านจากไฟล์ alldb.csv

,Unnamed: 0,user,RowKey,care,date,ov,phone,site,time,urine,pid,PartitionKey,title,age
0,0,test,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,data is not completed,data is not completed
1,1,04857,136FD222-FD9F-4E54-AE1F-7282A276B085,NaN,2022-02-24,NaN,"iPhone10,4",05310,10:50:32,NaN,NaN,NaN,data is not completed,data is not completed
2,2,NaN,1E6D3D62-4C8A-4F8E-90D1-0DC5BC2752DF.png,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,data is not completed,data is not completed
3,3,3450101576642,2D331FB0-CBA2-4586-A5B0-CB3CF44DD9FE,NaN,2022-02-23,0,"iPhone13,4",05087,09:59:47,ปกติ (เหลืองใส),NaN,NaN,data is not completed,data is not completed
4,4,3450101576642,45197AF7-7CB4-470C-9ABB-37C092BD6B21,NaN,2022-02-23,NaN,"iPhone13,4",05087,09:44:06,ปกติ (เหลืองใส),NaN,NaN,data is not completed,data is not completed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40030,40030,NaN,6B5FA20F-190E-4021-8547-C12308024C6C,NaN,NaN,NaN,"iPhone13,4",01234,NaN,NaN,5,เกษศิรินทร์ ไชยลาภ,data is not completed,data is not completed
40031,40031,NaN,F48C51C0-A345-40D6-93F4-46213267E1B1,NaN,NaN,2,"iPhone10,5",01234,NaN,ปกติ (เหลืองใส),5,เถลิงเกียรติ เสริฐเลิศ,data is not completed,data is not completed
40032,40032,NaN,A986BDAA-6D7C-4017-8E62-A3C104E946B9,NaN,NaN,1,"iPhone13,4",01234,NaN,ปกติ (เหลืองใส),1,เสรี,data is not completed,data is not completed
40033,40033,NaN,bbuogxulur.png,NaN,NaN,NaN,Samsung SM-A115F,01234,NaN,NaN,1,เสรี,data is not completed,data is not completed
40034,40034,NaN,zttpqogiso.png,NaN,NaN,1,Samsung SM-A115F,01234,NaN,ปกติ (เหลืองใส),1,เสรี,data is not completed,data is not completed

In [123]:
alldb.isnull().sum()

Unnamed: 0          0
user              762
RowKey              1
care            39963
date              554
ov                364
phone               3
site               99
time              557
urine             253
pid             39890
PartitionKey      185
title             444
age               542
dtype: int64

In [124]:
data_new_alldb = alldb[['user','RowKey','date','phone','site','time','urine','ov','PartitionKey']]
data_new_alldb

,user,RowKey,date,phone,site,time,urine,ov,PartitionKey
0,test,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,04857,136FD222-FD9F-4E54-AE1F-7282A276B085,2022-02-24,"iPhone10,4",05310,10:50:32,NaN,NaN,NaN
2,NaN,1E6D3D62-4C8A-4F8E-90D1-0DC5BC2752DF.png,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3450101576642,2D331FB0-CBA2-4586-A5B0-CB3CF44DD9FE,2022-02-23,"iPhone13,4",05087,09:59:47,ปกติ (เหลืองใส),0,NaN
4,3450101576642,45197AF7-7CB4-470C-9ABB-37C092BD6B21,2022-02-23,"iPhone13,4",05087,09:44:06,ปกติ (เหลืองใส),NaN,NaN
...,...,...,...,...,...,...,...,...,...
40030,NaN,6B5FA20F-190E-4021-8547-C12308024C6C,NaN,"iPhone13,4",01234,NaN,NaN,NaN,เกษศิรินทร์ ไชยลาภ
40031,NaN,F48C51C0-A345-40D6-93F4-46213267E1B1,NaN,"iPhone10,5",01234,NaN,ปกติ (เหลืองใส),2,เถลิงเกียรติ เสริฐเลิศ
40032,NaN,A986BDAA-6D7C-4017-8E62-A3C104E946B9,NaN,"iPhone13,4",01234,NaN,ปกติ (เหลืองใส),1,เสรี
40033,NaN,bbuogxulur.png,NaN,Samsung SM-A115F,01234,NaN,NaN,NaN,เสรี
40034,NaN,zttpqogiso.png,NaN,Samsung SM-A115F,01234,NaN,ปกติ (เหลืองใส),1,เสรี

In [125]:
data_new_alldb.isnull().sum()

user            762
RowKey            1
date            554
phone             3
site             99
time            557
urine           253
ov              364
PartitionKey    185
dtype: int64

In [126]:
dn_alldb_drop = data_new_alldb.dropna()
dn_alldb_drop #ใช้ตารางนี้ได้เลย

,user,RowKey,date,phone,site,time,urine,ov,PartitionKey
185,85879,shmpdrmtgc.png,2022-03-24,OPPO CPH2293,05194,13:08:39,มีตะกอน,0,0000
186,45-161,D2CABB8C-533B-450A-AFA6-B693749CC1C6,2022-02-23,"iPhone11,8",04312,09:45:28,ปกติ (เหลืองใส),0,0-1528
187,45-161,57A5F06C-C840-49EA-9514-A30D3C897CC8,2022-02-23,"iPhone11,8",04312,10:06:45,ปกติ (เหลืองใส),0,0-1544
188,27529,ADC54E82-4225-4DE6-89A6-A7E556C15FB1,2022-02-25,"iPhone13,1",04999,14:22:22,ปกติ (เหลืองใส),0,0000
190,06223,kfpwuaqldj.png,2022-03-23,Xiaomi 21081111RG,13777,16:31:45,ปกติ (เหลืองใส),0,00000
...,...,...,...,...,...,...,...,...,...
40013,ttest,crqcufokmn.png,2022-02-21,Samsung SM-G998B,test,14:23:45,ขุ่น,2,x001
40014,ttest,gzxgflnowr.png,2022-02-21,Samsung SM-G998B,test,14:23:43,ขุ่น,2,x001
40016,xxx,jytlopevha.png,2022-02-17,Samsung SM-N950F,xxx,00:01:06,ปกติ (เหลืองใส),3,xxx
40022,yyy,ivccsksowb.png,2022-02-17,Samsung SM-N950F,yyy,08:41:05,มีเม็ดเลือดแดง,2,yyy
40023,zzz,psudrnccsh.png,2022-02-17,Samsung SM-N950F,zzz,08:41:04,มีตะกอน,2,zzz

In [127]:
removes = data_new_alldb.shape[0] - dn_alldb_drop.shape[0]
print(f'size before drop = {data_new_alldb.shape[0]}')
print(f'size after drop = {dn_alldb_drop.shape[0]}')
print(f'% from drop = {(removes/data_new_alldb.shape[0])*100}')

size before drop = 40035
size after drop = 38663
% from drop = 3.427001373797927

In [128]:
set(dn_alldb_drop['site'])

{' 0502',
 '00004',
 '00006',
 '00007',
 '00008',
 '00012',
 '00016',
 '00017',
 '00018',
 '00027',
 '00028',
 '00040',
 '00052',
 '00055',
 '00061',
 '00069',
 '00070',
 '00071',
 '00081',
 '00082',
 '00090',
 '00094',
 '00096',
 '00108',
 '00109',
 '00115',
 '00120',
 '00122',
 '00127',
 '00163',
 '00164',
 '00165',
 '00166',
 '00169',
 '00170',
 '00171',
 '00173',
 '00174',
 '00176',
 '00177',
 '00178',
 '00179',
 '00180',
 '00182',
 '00185',
 '00186',
 '00187',
 '00189',
 '00190',
 '00191',
 '00192',
 '00193',
 '00194',
 '00195',
 '00196',
 '00197',
 '00198',
 '00200',
 '00202',
 '00204',
 '00205',
 '00206',
 '00207',
 '00209',
 '00213',
 '00214',
 '00217',
 '00218',
 '00219',
 '00229',
 '00232',
 '00235',
 '00240',
 '00247',
 '00266',
 '00271',
 '00279',
 '00323',
 '00331',
 '00333',
 '00346',
 '00348',
 '00381',
 '00382',
 '00385',
 '00387',
 '00388',
 '00389',
 '00390',
 '00391',
 '00394',
 '00397',
 '00400',
 '00401',
 '00404',
 '00406',
 '00408',
 '00410',
 '00411',
 '00412',
 '00413',
 '00414',
 '00415',
 '00512',
 '00513',
 '00579',
 '00580',
 '00956',
 '01151',
 '02038',
 '02414',
 '02536',
 '02759',
 '03432',
 '03616',
 '03626',
 '04275',
 '04279',
 '04280',
 '04281',
 '043.1',
 '04302',
 '04312',
 '04313',
 '04321',
 '04322',
 '04326',
 '04337',
 '04347',
 '04348',
 '04349',
 '04351',
 '04352',
 '04355',
 '04374',
 '04376',
 '04380',
 '04384',
 '04387',
 '04388',
 '04390',
 '04391',
 '04396',
 '04399',
 '04401',
 '04402',
 '04403',
 '04404',
 '04405',
 '04406',
 '04407',
 '04408',
 '04433',
 '04434',
 '04435',
 '04436',
 '04437',
 '04438',
 '04441',
 '04443',
 '04455',
 '04456',
 '04457',
 '04458',
 '04475',
 '04478',
 '04558',
 '04936',
 '04968',
 '04970',
 '04971',
 '04973',
 '04974',
 '04977',
 '04980',
 '04981',
 '04982',
 '04983',
 '04984',
 '04985',
 '04986',
 '04989',
 '04990',
 '04992',
 '04993',
 '04994',
 '04995',
 '04996',
 '04997',
 '04999',
 '05000',
 '05001',
 '05002',
 '05003',
 '05004',
 '05005',
 '05006',
 '05007',
 '05008',
 '05009',
 '05010',
 '05011',
 '05012',
 '05013',
 '05015',
 '05016',
 '05019',
 '05021',
 '05022',
 '05023',
 '05024',
 '05025',
 '05026',
 '05027',
 '05028',
 '05029',
 '05032',
 '05033',
 '05034',
 '05035',
 '05038',
 '05040',
 '05042',
 '05044',
 '05045',
 '05047',
 '05048',
 '05049',
 '05052',
 '05054',
 '05055',
 '05058',
 '05059',
 '05060',
 '05061',
 '05062',
 '05063',
 '05064',
 '05065',
 '05066',
 '05067',
 '05068',
 '05069',
 '05072',
 '05074',
 '05075',
 '05077',
 '05079',
 '05080',
 '05081',
 '05082',
 '05083',
 '05084',
 '05086',
 '05087',
 '05087\n',
 '05088',
 '05090',
 '05091',
 '05094',
 '05097',
 '05098',
 '05100',
 '05101',
 '05102',
 '05103',
 '05107',
 '05111',
 '05112',
 '05113',
 '05115',
 '05116',
 '05117',
 '05119',
 '05120',
 '05123',
 '05125',
 '05126',
 '05128',
 '05129',
 '05131',
 '05132',
 '05133',
 '05135',
 '05136',
 '05141',
 '05143',
 '05144',
 '05146',
 '05147',
 '05152',
 '05154',
 '05157',
 '05158',
 '05162',
 '05166',
 '05172',
 '05173',
 '05175',
 '05177',
 '05178',
 '05180',
 '05181',
 '05182',
 '05185',
 '05187',
 '05188',
 '05192',
 '05193',
 '05194',
 '05195',
 '05196',
 '05198',
 '05200',
 '05203',
 '05205',
 '05207',
 '05210',
 '05211',
 '05213',
 '05214',
 '05215',
 '05219',
 '05220',
 '05222',
 '05223',
 '05224',
 '05225',
 '05226',
 '05228',
 '05229',
 '05233',
 '05236',
 '05237',
 '05238',
 '05240',
 '05241',
 '05242',
 '05244',
 '05245',
 '05246',
 '05247',
 '05248',
 '05249',
 '05250',
 '05250\n',
 '05251',
 '05252',
 '05253',
 '05254',
 '05255',
 '05256',
 '05257',
 '05258',
 '05259',
 '05260',
 '05261',
 '05264',
 '05265',
 '05291',
 '05298',
 '05300',
 '05304',
 '05310',
 '05311',
 '05312',
 '05313',
 '05314',
 '05315',
 '05316',
 '05322',
 '05323',
 '05324',
 '05325',
 '05327',
 '05328',
 '05332',
 '05335',
 '05337',
 '05338',
 '05339',
 '05340',
 '05343',
 '05344',
 '05345',
 '05346',
 '05349',
 '05350',
 '05350ยอ',
 '05351',
 '05352',
 '05354',
 '05355',
 '05356',
 '05357',
 '05358',
 '05359',
 '05360',
 '05361',
 '05363',
 '05365',
 '05366',
 '05367',
 '05368',
 '05370',
 '05371',
 '05373',
 '05378',
 '05386',
 '05391',
 '05392',
 '05393',
 '05394',
 '05395',
 '05396',
 '05399',
 '05413',
 '05414',
 '05415',
 '05416',
 '05418',
 '05419',
 '05422',
 '05423',
 '05424',
 '05425',
 '05428',
 '05431',
 '05432',
 '05433',
 '05434',
 '05435',
 '05436',
 '05437',
 '05439',
 '05440',
 '05441',
 '05442',
 '05541',
 '06238',
 '06251',
 '06253',
 '06254',
 '06255',
 '06256',
 '06257',
 '06259',
 '06260',
 '06261',
 '06263',
 '06265',
 '06267',
 '06268',
 '06270',
 '06271',
 '06272',
 '06273',
 '06274',
 '06275',
 '06276',
 '06277',
 '06278',
 '06279',
 '06280',
 '06281',
 '06282',
 '06283',
 '06285',
 '06286',
 '06287',
 '06288',
 '06289',
 '06290',
 '06291',
 '06292',
 '06293',
 '06294',
 '06295',
 '06296',
 '06297',
 '06298',
 '06299',
 '06300',
 '06301',
 '06302',
 '06307',
 '06308',
 '06309',
 '06310',
 '06311',
 '06312',
 '06314',
 '06315',
 '06316',
 '06318',
 '06319',
 '06320',
 '06321',
 '06322',
 '06323',
 '06324',
 '06325',
 '06326',
 '06327',
 '06328',
 '06329',
 '06330',
 '06331',
 '06332',
 '06333',
 '06334',
 '06521',
 '08485',
 '10360',
 '10673',
 '11010',
 '11055',
 '11056',
 '11057',
 '11059',
 '11060',
 '11066',
 '11069',
 '11070',
 '11072',
 '11073',
 '11084',
 '11088',
 '11111',
 '11111111',
 '11158',
 '11159',
 '11160',
 '11161',
 '11163',
 '11164',
 '11165',
 '11740',
 '11748',
 '11749',
 '11800',
 '11887',
 '13777',
 '13777t',
 '13937',
 '13941',
 '13943',
 '13943\n\n',
 '13944',
 '13946',
 '13947',
 '13948',
 '13949',
 '13952',
 '13953',
 '13954',
 '13955',
 '13962',
 '13963',
 '13966',
 '13984',
 '13987',
 '14005',
 '14007',
 '14280',
 '14284',
 '14843',
 '20510',
 '22222',
 '24622',
 '24650',
 '27988',
 '27990',
 '27998',
 '28017',
 '28691',
 '28789',
 '33333',
 '44902',
 '45972',
 '49741',
 '50210',
 '5271',
 '55555',
 '66666',
 '75757',
 '88888',
 '97255',
 '99795',
 '99999',
 'aaa',
 'bbb',
 'ccc',
 'eee',
 'fff',
 'ggg',
 'hhh',
 'iii',
 'jjj',
 'kkk',
 'lll',
 'mmm',
 'ppp',
 'qqq',
 'rrr',
 'sss',
 'test',
 'ttt',
 'uuu',
 'vvv',
 'www',
 'xxx',
 'yyy',
 'zzz'}

In [129]:
dn_alldb_drop['site'].replace({' 0502':'ไม่ระบุ',
                            '05087\n':'05087',
                            '05250\n':'05250',
                            '05350ยอ':'05350',
                            '11111111':'11111',
                            '13777t':'13777',
                            '13943\n\n':'13943',
                            '5271':'ไม่ระบุ',
                            'aaa':'ไม่ระบุ',
                            'bbb':'ไม่ระบุ',
                            'ccc':'ไม่ระบุ',
                            'eee':'ไม่ระบุ',
                            'fff':'ไม่ระบุ',
                            'ggg':'ไม่ระบุ',
                            'hhh':'ไม่ระบุ',
                            'iii':'ไม่ระบุ',
                            'jjj':'ไม่ระบุ',
                            'kkk':'ไม่ระบุ',
                            'lll':'ไม่ระบุ',
                            'mmm':'ไม่ระบุ',
                            'ppp':'ไม่ระบุ',
                            'qqq':'ไม่ระบุ',
                            'rrr':'ไม่ระบุ',
                            'sss':'ไม่ระบุ',
                            'test':'ไม่ระบุ',
                            'ttt':'ไม่ระบุ',
                            'uuu':'ไม่ระบุ',
                            'vvv':'ไม่ระบุ',
                            'www':'ไม่ระบุ',
                            'xxx':'ไม่ระบุ',
                            'yyy':'ไม่ระบุ',
                            'zzz':'ไม่ระบุ',
                            '043.1':'ไม่ระบุ'}, inplace=True)

/usr/local/lib/python3.7/dist-packages/pandas/core/generic.py:6619: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return self._update_inplace(result)

In [130]:
set(dn_alldb_drop['site'])

{'00004',
 '00006',
 '00007',
 '00008',
 '00012',
 '00016',
 '00017',
 '00018',
 '00027',
 '00028',
 '00040',
 '00052',
 '00055',
 '00061',
 '00069',
 '00070',
 '00071',
 '00081',
 '00082',
 '00090',
 '00094',
 '00096',
 '00108',
 '00109',
 '00115',
 '00120',
 '00122',
 '00127',
 '00163',
 '00164',
 '00165',
 '00166',
 '00169',
 '00170',
 '00171',
 '00173',
 '00174',
 '00176',
 '00177',
 '00178',
 '00179',
 '00180',
 '00182',
 '00185',
 '00186',
 '00187',
 '00189',
 '00190',
 '00191',
 '00192',
 '00193',
 '00194',
 '00195',
 '00196',
 '00197',
 '00198',
 '00200',
 '00202',
 '00204',
 '00205',
 '00206',
 '00207',
 '00209',
 '00213',
 '00214',
 '00217',
 '00218',
 '00219',
 '00229',
 '00232',
 '00235',
 '00240',
 '00247',
 '00266',
 '00271',
 '00279',
 '00323',
 '00331',
 '00333',
 '00346',
 '00348',
 '00381',
 '00382',
 '00385',
 '00387',
 '00388',
 '00389',
 '00390',
 '00391',
 '00394',
 '00397',
 '00400',
 '00401',
 '00404',
 '00406',
 '00408',
 '00410',
 '00411',
 '00412',
 '00413',
 '00414',
 '00415',
 '00512',
 '00513',
 '00579',
 '00580',
 '00956',
 '01151',
 '02038',
 '02414',
 '02536',
 '02759',
 '03432',
 '03616',
 '03626',
 '04275',
 '04279',
 '04280',
 '04281',
 '04302',
 '04312',
 '04313',
 '04321',
 '04322',
 '04326',
 '04337',
 '04347',
 '04348',
 '04349',
 '04351',
 '04352',
 '04355',
 '04374',
 '04376',
 '04380',
 '04384',
 '04387',
 '04388',
 '04390',
 '04391',
 '04396',
 '04399',
 '04401',
 '04402',
 '04403',
 '04404',
 '04405',
 '04406',
 '04407',
 '04408',
 '04433',
 '04434',
 '04435',
 '04436',
 '04437',
 '04438',
 '04441',
 '04443',
 '04455',
 '04456',
 '04457',
 '04458',
 '04475',
 '04478',
 '04558',
 '04936',
 '04968',
 '04970',
 '04971',
 '04973',
 '04974',
 '04977',
 '04980',
 '04981',
 '04982',
 '04983',
 '04984',
 '04985',
 '04986',
 '04989',
 '04990',
 '04992',
 '04993',
 '04994',
 '04995',
 '04996',
 '04997',
 '04999',
 '05000',
 '05001',
 '05002',
 '05003',
 '05004',
 '05005',
 '05006',
 '05007',
 '05008',
 '05009',
 '05010',
 '05011',
 '05012',
 '05013',
 '05015',
 '05016',
 '05019',
 '05021',
 '05022',
 '05023',
 '05024',
 '05025',
 '05026',
 '05027',
 '05028',
 '05029',
 '05032',
 '05033',
 '05034',
 '05035',
 '05038',
 '05040',
 '05042',
 '05044',
 '05045',
 '05047',
 '05048',
 '05049',
 '05052',
 '05054',
 '05055',
 '05058',
 '05059',
 '05060',
 '05061',
 '05062',
 '05063',
 '05064',
 '05065',
 '05066',
 '05067',
 '05068',
 '05069',
 '05072',
 '05074',
 '05075',
 '05077',
 '05079',
 '05080',
 '05081',
 '05082',
 '05083',
 '05084',
 '05086',
 '05087',
 '05088',
 '05090',
 '05091',
 '05094',
 '05097',
 '05098',
 '05100',
 '05101',
 '05102',
 '05103',
 '05107',
 '05111',
 '05112',
 '05113',
 '05115',
 '05116',
 '05117',
 '05119',
 '05120',
 '05123',
 '05125',
 '05126',
 '05128',
 '05129',
 '05131',
 '05132',
 '05133',
 '05135',
 '05136',
 '05141',
 '05143',
 '05144',
 '05146',
 '05147',
 '05152',
 '05154',
 '05157',
 '05158',
 '05162',
 '05166',
 '05172',
 '05173',
 '05175',
 '05177',
 '05178',
 '05180',
 '05181',
 '05182',
 '05185',
 '05187',
 '05188',
 '05192',
 '05193',
 '05194',
 '05195',
 '05196',
 '05198',
 '05200',
 '05203',
 '05205',
 '05207',
 '05210',
 '05211',
 '05213',
 '05214',
 '05215',
 '05219',
 '05220',
 '05222',
 '05223',
 '05224',
 '05225',
 '05226',
 '05228',
 '05229',
 '05233',
 '05236',
 '05237',
 '05238',
 '05240',
 '05241',
 '05242',
 '05244',
 '05245',
 '05246',
 '05247',
 '05248',
 '05249',
 '05250',
 '05251',
 '05252',
 '05253',
 '05254',
 '05255',
 '05256',
 '05257',
 '05258',
 '05259',
 '05260',
 '05261',
 '05264',
 '05265',
 '05291',
 '05298',
 '05300',
 '05304',
 '05310',
 '05311',
 '05312',
 '05313',
 '05314',
 '05315',
 '05316',
 '05322',
 '05323',
 '05324',
 '05325',
 '05327',
 '05328',
 '05332',
 '05335',
 '05337',
 '05338',
 '05339',
 '05340',
 '05343',
 '05344',
 '05345',
 '05346',
 '05349',
 '05350',
 '05351',
 '05352',
 '05354',
 '05355',
 '05356',
 '05357',
 '05358',
 '05359',
 '05360',
 '05361',
 '05363',
 '05365',
 '05366',
 '05367',
 '05368',
 '05370',
 '05371',
 '05373',
 '05378',
 '05386',
 '05391',
 '05392',
 '05393',
 '05394',
 '05395',
 '05396',
 '05399',
 '05413',
 '05414',
 '05415',
 '05416',
 '05418',
 '05419',
 '05422',
 '05423',
 '05424',
 '05425',
 '05428',
 '05431',
 '05432',
 '05433',
 '05434',
 '05435',
 '05436',
 '05437',
 '05439',
 '05440',
 '05441',
 '05442',
 '05541',
 '06238',
 '06251',
 '06253',
 '06254',
 '06255',
 '06256',
 '06257',
 '06259',
 '06260',
 '06261',
 '06263',
 '06265',
 '06267',
 '06268',
 '06270',
 '06271',
 '06272',
 '06273',
 '06274',
 '06275',
 '06276',
 '06277',
 '06278',
 '06279',
 '06280',
 '06281',
 '06282',
 '06283',
 '06285',
 '06286',
 '06287',
 '06288',
 '06289',
 '06290',
 '06291',
 '06292',
 '06293',
 '06294',
 '06295',
 '06296',
 '06297',
 '06298',
 '06299',
 '06300',
 '06301',
 '06302',
 '06307',
 '06308',
 '06309',
 '06310',
 '06311',
 '06312',
 '06314',
 '06315',
 '06316',
 '06318',
 '06319',
 '06320',
 '06321',
 '06322',
 '06323',
 '06324',
 '06325',
 '06326',
 '06327',
 '06328',
 '06329',
 '06330',
 '06331',
 '06332',
 '06333',
 '06334',
 '06521',
 '08485',
 '10360',
 '10673',
 '11010',
 '11055',
 '11056',
 '11057',
 '11059',
 '11060',
 '11066',
 '11069',
 '11070',
 '11072',
 '11073',
 '11084',
 '11088',
 '11111',
 '11158',
 '11159',
 '11160',
 '11161',
 '11163',
 '11164',
 '11165',
 '11740',
 '11748',
 '11749',
 '11800',
 '11887',
 '13777',
 '13937',
 '13941',
 '13943',
 '13944',
 '13946',
 '13947',
 '13948',
 '13949',
 '13952',
 '13953',
 '13954',
 '13955',
 '13962',
 '13963',
 '13966',
 '13984',
 '13987',
 '14005',
 '14007',
 '14280',
 '14284',
 '14843',
 '20510',
 '22222',
 '24622',
 '24650',
 '27988',
 '27990',
 '27998',
 '28017',
 '28691',
 '28789',
 '33333',
 '44902',
 '45972',
 '49741',
 '50210',
 '55555',
 '66666',
 '75757',
 '88888',
 '97255',
 '99795',
 '99999',
 'ไม่ระบุ'}

In [131]:
data_file_path2 = os.path.join(path,'hospital_list.xlsx') 
hospital_list = pd.read_excel(data_file_path2)
hospital_list #ตารางแสดงการอ่านจากไฟล์ hospital_list.xlsx

,hcode,name,zone_code,zone_name,provincecode,province,amphurcode,amphur,tamboncode,tambon,code4,name5,code9,name10,short_thai,short_english
0,00001,สำนักงานสาธารณสุขจังหวัดสมุทรปราการ,6,สาขาพื้นที่(ระยอง),11.0,สมุทรปราการ,1.0,เมืองสมุทรปราการ,1.0,ปากน้ำ,1.0,สำนักงานสาธารณสุขจังหวัด,NaN,NaN,สป,SPK
1,00002,สำนักงานสาธารณสุขจังหวัดนนทบุรี,4,สาขาพื้นที่(สระบุรี),12.0,นนทบุรี,1.0,เมืองนนทบุรี,4.0,บางกระสอ,1.0,สำนักงานสาธารณสุขจังหวัด,NaN,NaN,นบ,NBI
2,00003,สำนักงานสาธารณสุขจังหวัดปทุมธานี,4,สาขาพื้นที่(สระบุรี),13.0,ปทุมธานี,1.0,เมืองปทุมธานี,1.0,บางปรอก,1.0,สำนักงานสาธารณสุขจังหวัด,NaN,NaN,ปท,PTE
3,00004,สำนักงานสาธารณสุขจังหวัดพระนครศรีอยุธยา,4,สาขาพื้นที่(สระบุรี),14.0,พระนครศรีอยุธยา,1.0,พระนครศรีอยุธยา,3.0,หอรัตนไชย,1.0,สำนักงานสาธารณสุขจังหวัด,NaN,NaN,อย,AYA
4,00005,สำนักงานสาธารณสุขจังหวัดอ่างทอง,4,สาขาพื้นที่(สระบุรี),15.0,อ่างทอง,1.0,เมืองอ่างทอง,8.0,บ้านอิฐ,1.0,สำนักงานสาธารณสุขจังหวัด,NaN,NaN,อท,ATG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17098,99990,ศูนย์สุขภาพชุมชนโรงพยาบาลอุตรดิตถ์(สาขา 2 วัดท...,2,สาขาพื้นที่(พิษณุโลก),53.0,อุตรดิตถ์,1.0,เมืองอุตรดิตถ์,1.0,ท่าอิฐ,8.0,ศูนย์สุขภาพชุมชน ของ รพ.,10.0,1 ปฐมภูมิ,อต,UTT
17099,99991,ศูนย์สุขภาพชุมชนโรงพยาบาลกุยบุรี,5,สาขาพื้นที่(ราชบุรี),77.0,ประจวบคีรีขันธ์,2.0,กุยบุรี,1.0,กุยบุรี,8.0,ศูนย์สุขภาพชุมชน ของ รพ.,10.0,1 ปฐมภูมิ,ปข,PKN
17100,99993,ศูนย์สุขภาพชุมชนตำบลวัดเพลง,5,สาขาพื้นที่(ราชบุรี),70.0,ราชบุรี,9.0,วัดเพลง,3.0,วัดเพลง,8.0,ศูนย์สุขภาพชุมชน ของ รพ.,10.0,1 ปฐมภูมิ,รบ,RBR
17101,99996,คลินิกทันตกรรม สสจ.ศรีสะเกษ,10,สาขาพื้นที่(อุบลราชธานี),33.0,ศรีสะเกษ,1.0,เมืองศรีสะเกษ,11.0,โพนข่า,8.0,ศูนย์สุขภาพชุมชน ของ รพ.,10.0,1 ปฐมภูมิ,ศก,SSK
17102,99998,ศูนย์สุขภาพชุมชนตำบลบางแพ,5,สาขาพื้นที่(ราชบุรี),70.0,ราชบุรี,6.0,บางแพ,2.0,วังเย็น,8.0,ศูนย์สุขภาพชุมชน ของ รพ.,10.0,1 ปฐมภูมิ,รบ,RBR

In [132]:
hospital_list.isnull().sum()

hcode               0
name                1
zone_code           0
zone_name           4
provincecode        1
province            0
amphurcode          2
amphur              2
tamboncode        168
tambon            209
code4               1
name5               3
code9            5294
name10           5294
short_thai          6
short_english       6
dtype: int64

In [133]:
new_hospital = hospital_list[['hcode',	'name',	'zone_code',	'zone_name',	'provincecode',	'province',	'amphurcode',	'amphur',	'tamboncode',	'tambon']]
new_hospital

,hcode,name,zone_code,zone_name,provincecode,province,amphurcode,amphur,tamboncode,tambon
0,00001,สำนักงานสาธารณสุขจังหวัดสมุทรปราการ,6,สาขาพื้นที่(ระยอง),11.0,สมุทรปราการ,1.0,เมืองสมุทรปราการ,1.0,ปากน้ำ
1,00002,สำนักงานสาธารณสุขจังหวัดนนทบุรี,4,สาขาพื้นที่(สระบุรี),12.0,นนทบุรี,1.0,เมืองนนทบุรี,4.0,บางกระสอ
2,00003,สำนักงานสาธารณสุขจังหวัดปทุมธานี,4,สาขาพื้นที่(สระบุรี),13.0,ปทุมธานี,1.0,เมืองปทุมธานี,1.0,บางปรอก
3,00004,สำนักงานสาธารณสุขจังหวัดพระนครศรีอยุธยา,4,สาขาพื้นที่(สระบุรี),14.0,พระนครศรีอยุธยา,1.0,พระนครศรีอยุธยา,3.0,หอรัตนไชย
4,00005,สำนักงานสาธารณสุขจังหวัดอ่างทอง,4,สาขาพื้นที่(สระบุรี),15.0,อ่างทอง,1.0,เมืองอ่างทอง,8.0,บ้านอิฐ
...,...,...,...,...,...,...,...,...,...,...
17098,99990,ศูนย์สุขภาพชุมชนโรงพยาบาลอุตรดิตถ์(สาขา 2 วัดท...,2,สาขาพื้นที่(พิษณุโลก),53.0,อุตรดิตถ์,1.0,เมืองอุตรดิตถ์,1.0,ท่าอิฐ
17099,99991,ศูนย์สุขภาพชุมชนโรงพยาบาลกุยบุรี,5,สาขาพื้นที่(ราชบุรี),77.0,ประจวบคีรีขันธ์,2.0,กุยบุรี,1.0,กุยบุรี
17100,99993,ศูนย์สุขภาพชุมชนตำบลวัดเพลง,5,สาขาพื้นที่(ราชบุรี),70.0,ราชบุรี,9.0,วัดเพลง,3.0,วัดเพลง
17101,99996,คลินิกทันตกรรม สสจ.ศรีสะเกษ,10,สาขาพื้นที่(อุบลราชธานี),33.0,ศรีสะเกษ,1.0,เมืองศรีสะเกษ,11.0,โพนข่า
17102,99998,ศูนย์สุขภาพชุมชนตำบลบางแพ,5,สาขาพื้นที่(ราชบุรี),70.0,ราชบุรี,6.0,บางแพ,2.0,วังเย็น

In [134]:
new_hospital.isnull().sum()

hcode             0
name              1
zone_code         0
zone_name         4
provincecode      1
province          0
amphurcode        2
amphur            2
tamboncode      168
tambon          209
dtype: int64

In [135]:
dn_hospital_drop = new_hospital.dropna()
dn_hospital_drop

,hcode,name,zone_code,zone_name,provincecode,province,amphurcode,amphur,tamboncode,tambon
0,00001,สำนักงานสาธารณสุขจังหวัดสมุทรปราการ,6,สาขาพื้นที่(ระยอง),11.0,สมุทรปราการ,1.0,เมืองสมุทรปราการ,1.0,ปากน้ำ
1,00002,สำนักงานสาธารณสุขจังหวัดนนทบุรี,4,สาขาพื้นที่(สระบุรี),12.0,นนทบุรี,1.0,เมืองนนทบุรี,4.0,บางกระสอ
2,00003,สำนักงานสาธารณสุขจังหวัดปทุมธานี,4,สาขาพื้นที่(สระบุรี),13.0,ปทุมธานี,1.0,เมืองปทุมธานี,1.0,บางปรอก
3,00004,สำนักงานสาธารณสุขจังหวัดพระนครศรีอยุธยา,4,สาขาพื้นที่(สระบุรี),14.0,พระนครศรีอยุธยา,1.0,พระนครศรีอยุธยา,3.0,หอรัตนไชย
4,00005,สำนักงานสาธารณสุขจังหวัดอ่างทอง,4,สาขาพื้นที่(สระบุรี),15.0,อ่างทอง,1.0,เมืองอ่างทอง,8.0,บ้านอิฐ
...,...,...,...,...,...,...,...,...,...,...
17098,99990,ศูนย์สุขภาพชุมชนโรงพยาบาลอุตรดิตถ์(สาขา 2 วัดท...,2,สาขาพื้นที่(พิษณุโลก),53.0,อุตรดิตถ์,1.0,เมืองอุตรดิตถ์,1.0,ท่าอิฐ
17099,99991,ศูนย์สุขภาพชุมชนโรงพยาบาลกุยบุรี,5,สาขาพื้นที่(ราชบุรี),77.0,ประจวบคีรีขันธ์,2.0,กุยบุรี,1.0,กุยบุรี
17100,99993,ศูนย์สุขภาพชุมชนตำบลวัดเพลง,5,สาขาพื้นที่(ราชบุรี),70.0,ราชบุรี,9.0,วัดเพลง,3.0,วัดเพลง
17101,99996,คลินิกทันตกรรม สสจ.ศรีสะเกษ,10,สาขาพื้นที่(อุบลราชธานี),33.0,ศรีสะเกษ,1.0,เมืองศรีสะเกษ,11.0,โพนข่า
17102,99998,ศูนย์สุขภาพชุมชนตำบลบางแพ,5,สาขาพื้นที่(ราชบุรี),70.0,ราชบุรี,6.0,บางแพ,2.0,วังเย็น

In [136]:
dn_hospital_drop.isnull().sum()

hcode           0
name            0
zone_code       0
zone_name       0
provincecode    0
province        0
amphurcode      0
amphur          0
tamboncode      0
tambon          0
dtype: int64

In [137]:
removes = new_hospital.shape[0] - dn_hospital_drop.shape[0]
print(f'size before drop = {data_new_alldb.shape[0]}')
print(f'size after drop = {new_hospital.shape[0]}')
print(f'% from drop = {(removes/new_hospital.shape[0])*100}')

size before drop = 40035
size after drop = 17103
% from drop = 1.245395544641291

In [138]:
set(dn_hospital_drop['hcode'])

{'05994',
 '10006',
 '17429',
 '21336',
 '02624',
 '24321',
 '14434',
 '03812',
 '03974',
 '07933',
 '08586',
 '24624',
 '08316',
 '06975',
 '01439',
 '03863',
 '14066',
 '10117',
 '03442',
 '04147',
 '00779',
 '04613',
 '14697',
 '07429',
 '09040',
 '04014',
 '09538',
 '25909',
 '00266',
 '03878',
 '07861',
 '08165',
 '10863',
 '05653',
 '03721',
 '12284',
 '05722',
 '01232',
 '04302',
 '07762',
 '10155',
 '00332',
 '27015',
 '01920',
 '05223',
 '06367',
 '24951',
 '26634',
 '09751',
 '99860',
 '07114',
 '15132',
 '15200',
 '05293',
 '06071',
 '14145',
 '06173',
 '07277',
 '14286',
 '04753',
 '00021',
 '01172',
 '05259',
 '05342',
 '09118',
 '02752',
 '10178',
 '00567',
 '27340',
 '07522',
 '09448',
 '06386',
 '25775',
 '02484',
 '05265',
 '09400',
 '06338',
 '07794',
 '01322',
 '06979',
 '22524',
 '04459',
 '02749',
 '01603',
 '00573',
 '04551',
 '05231',
 '07721',
 '03930',
 '08506',
 '10798',
 '05273',
 '02370',
 '06345',
 '23232',
 '03758',
 '02989',
 '11122',
 '22764',
 '13962',
 '04137',
 '05886',
 '07887',
 '09923',
 '24406',
 '26326',
 '07208',
 '26014',
 '01061',
 '99863',
 '14092',
 '01849',
 '24280',
 '09482',
 '09211',
 '00267',
 '99935',
 '05011',
 '13880',
 '00426',
 '25157',
 '01736',
 '01250',
 '10740',
 '09756',
 '02066',
 '25651',
 '26052',
 '01452',
 '03509',
 '04187',
 '05891',
 '06164',
 '06262',
 '07938',
 '09048',
 '07506',
 '09795',
 '23609',
 '24179',
 '08530',
 '01737',
 '06297',
 '24147',
 '14103',
 '14080',
 '03661',
 '09944',
 '00798',
 '04226',
 '06359',
 '21526',
 '04156',
 '08324',
 '19398',
 '03440',
 '28846',
 '12235',
 '00519',
 '19407',
 '99909',
 '26932',
 '00795',
 '01179',
 '14187',
 '04959',
 '01215',
 '04840',
 '15176',
 '09978',
 '00298',
 '27617',
 '06947',
 '01464',
 '02656',
 '08011',
 '99953',
 '11578',
 '00294',
 '03291',
 '08077',
 '07992',
 '08752',
 '00299',
 '03408',
 '00899',
 '08254',
 '01402',
 '10876',
 '77737',
 '08598',
 '00247',
 '24329',
 '01162',
 '04929',
 '07644',
 '24074',
 '05815',
 '05359',
 '07067',
 '18609',
 '04032',
 '08599',
 '27471',
 '00709',
 '08190',
 '26315',
 '04297',
 '11828',
 '08945',
 '05836',
 '04272',
 '22059',
 '25701',
 '27404',
 '01256',
 '22953',
 '07639',
 '06154',
 '10101',
 '08343',
 '01008',
 '03844',
 '24770',
 '02601',
 '03030',
 '25719',
 '28149',
 '01094',
 '24058',
 '14256',
 '05847',
 '26844',
 '04175',
 '02589',
 '01176',
 '04132',
 '04667',
 '08823',
 '06612',
 '04737',
 '04444',
 '24021',
 '01974',
 '28784',
 '06891',
 '09038',
 '06619',
 '25117',
 '03686',
 '24675',
 '03394',
 '25728',
 '02843',
 '27630',
 '05719',
 '06284',
 '08758',
 '09758',
 '06054',
 '25024',
 '08471',
 '26124',
 '14374',
 '10432',
 '05951',
 '09421',
 '25836',
 '12026',
 '26594',
 '02674',
 '00381',
 '02463',
 '05027',
 '11717',
 '09661',
 '26885',
 '24143',
 '09136',
 '25704',
 '03474',
 '01847',
 '00076',
 '24235',
 '24392',
 '01046',
 '28775',
 '03989',
 '06428',
 '05333',
 '05819',
 '08469',
 '23648',
 '09752',
 '01935',
 '25759',
 '00639',
 '15186',
 '01862',
 '05115',
 '00493',
 '09424',
 '08479',
 '26923',
 '08855',
 '04599',
 '06996',
 '27732',
 '03485',
 '77726',
 '04126',
 '03299',
 '01424',
 '01433',
 '09598',
 '03466',
 '11668',
 '15299',
 '21485',
 '13713',
 '14621',
 '17926',
 '04083',
 '02890',
 '09886',
 '24069',
 '03195',
 '11493',
 '14055',
 '15139',
 '05452',
 '03257',
 '22302',
 '08116',
 '27014',
 '28022',
 '07633',
 '25131',
 '05055',
 '27347',
 '05617',
 '04425',
 '27046',
 '04154',
 '21970',
 '01783',
 '09289',
 '08426',
 '13824',
 '02861',
 '14045',
 '28857',
 '08224',
 '08398',
 '08309',
 '01005',
 '03486',
 '06363',
 '08345',
 '05395',
 '01447',
 '27060',
 '14308',
 '01129',
 '06396',
 '25763',
 '04997',
 '27649',
 '12033',
 '28776',
 '05679',
 '25183',
 '05535',
 '02836',
 '09776',
 '03206',
 '08993',
 '12056',
 '14437',
 '17043',
 '00849',
 '08541',
 '09685',
 '29636',
 '28717',
 '06303',
 '03497',
 '10071',
 '02036',
 '11083',
 '08302',
 '07027',
 '09102',
 '25681',
 '10392',
 '06846',
 '01406',
 '25001',
 '23539',
 '01900',
 '00768',
 '02402',
 '77672',
 '07031',
 '00178',
 '08474',
 '10417',
 '02427',
 '23220',
 '04703',
 '03966',
 '05948',
 '23716',
 '26799',
 '27547',
 '28730',
 '13699',
 '11470',
 '03511',
 '24841',
 '24966',
 '01535',
 '23994',
 '08704',
 '06172',
 '06720',
 '03122',
 '05396',
 '11990',
 '12049',
 '28821',
 '01507',
 '05434',
 '07200',
 '16881',
 '24746',
 '28738',
 '07336',
 '24149',
 '04373',
 '09555',
 '07446',
 '13649',
 '09814',
 '24923',
 '24310',
 '23766',
 '05158',
 '06662',
 '28697',
 '11955',
 '24914',
 '26331',
 '03514',
 '09708',
 '05623',
 '14094',
 '05907',
 '09947',
 '27694',
 '09650',
 '09284',
 '00716',
 '08714',
 '01419',
 '01617',
 '07605',
 '22767',
 '05485',
 '28761',
 '05637',
 '13967',
 '06077',
 '11479',
 '02996',
 '27051',
 '07860',
 '10458',
 '19448',
 '25975',
 '04249',
 '07103',
 '10397',
 '12221',
 '03446',
 '28695',
 '77692',
 '15004',
 '01651',
 '23212',
 '23475',
 '04274',
 '26103',
 '04858',
 '24034',
 '09768',
 '09838',
 '11164',
 '03034',
 '04350',
 '05368',
 '12446',
 '04621',
 '09639',
 '00885',
 '08739',
 '21747',
 '16140',
 '00904',
 '22742',
 '10199',
 '11455',
 '24527',
 '24111',
 '03939',
 '26683',
 '19482',
 '04397',
 '09131',
 '13831',
 '04347',
 '06513',
 '05852',
 '10667',
 '00916',
 '13882',
 '19408',
 '06003',
 '03786',
 '25959',
 '13876',
 '09285',
 '09673',
 '08707',
 '02267',
 '03093',
 '10878',
 '11002',
 '13697',
 '24057',
 '09913',
 '24003',
 '06936',
 '08810',
 '05224',
 '07240',
 '04288',
 '06377',
 '00233',
 '24820',
 '26740',
 '04740',
 '05498',
 '23267',
 '04386',
 '03624',
 '99795',
 '13828',
 '00123',
 '00889',
 '05267',
 '03001',
 '08448',
 '04195',
 '24812',
 '12290',
 '02837',
 '06646',
 '06311',
 '15177',
 '05555',
 '04796',
 '11628',
 '15214',
 '10666',
 '06318',
 '03841',
 '06009',
 '08673',
 '23068',
 '24868',
 '06764',
 '15201',
 '03228',
 '18009',
 '28287',
 '14713',
 '01086',
 '00799',
 '03346',
 '05185',
 '06316',
 '09414',
 '04688',
 '02215',
 '11528',
 '08529',
 '10532',
 '99899',
 '02860',
 '23574',
 '14617',
 '07097',
 '05227',
 '24695',
 '01628',
 '09542',
 '02676',
 '04641',
 '25789',
 '01915',
 '05053',
 '24082',
 '14431',
 '04113',
 '03534',
 '14839',
 '03312',
 '06277',
 '01555',
 '28699',
 '02411',
 '25446',
 '24869',
 '28759',
 '14470',
 '15249',
 '27653',
 '16936',
 '09577',
 '15066',
 '02200',
 '01360',
 '04333',
 '02638',
 '27691',
 '09980',
 '07371',
 '08100',
 '04923',
 '10216',
 '19579',
 '28690',
 '10796',
 '11208',
 '06469',
 '04646',
 '01394',
 '27446',
 '01623',
 '01384',
 '19374',
 '24862',
 '25456',
 '11181',
 '08043',
 '11104',
 '20021',
 '21714',
 '02854',
 '12419',
 '02308',
 '05370',
 '04687',
 '00169',
 '00773',
 '01295',
 '02101',
 '07460',
 '25914',
 '02056',
 '06511',
 '05003',
 '08432',
 '23159',
 '03887',
 '25828',
 '05089',
 '08580',
 '22777',
 '01998',
 '03149',
 '05652',
 '27449',
 '09737',
 '01460',
 '08029',
 '28078',
 '06851',
 '07549',
 '04802',
 '07628',
 '10836',
 '07929',
 '14040',
 '05581',
 '01278',
 '02168',
 '26953',
 '14961',
 '21584',
 '03625',
 '23998',
 '07406',
 '19457',
 '28039',
 '06973',
 '15141',
 '14017',
 '04865',
 '05825',
 '11168',
 '04381',
 '01431',
 '02706',
 '06952',
 '08875',
 '12069',
 '25749',
 '00070',
 '99813',
 '04787',
 '11415',
 '01804',
 '08851',
 '14457',
 '02274',
 '10459',
 '22829',
 '06162',
 '02325',
 '06298',
 '10185',
 '23631',
 '28168',
 '06391',
 '06820',
 '06934',
 '08238',
 '09588',
 '24045',
 '04624',
 '05253',
 '06230',
 '09169',
 '03588',
 '23565',
 '02819',
 '24654',
 '03008',
 '08028',
 '00221',
 '02925',
 '05232',
 '06586',
 '00619',
 '00229',
 '04693',
 '23795',
 '24760',
 '18521',
 '23554',
 '28032',
 '00662',
 '09543',
 '14709',
 '23821',
 '22849',
 '04394',
 '07248',
 '15128',
 '07091',
 '22687',
 '05923',
 '16702',
 '06112',
 '25004',
 '99991',
 '08853',
 '00186',
 '14096',
 '09766',
 '28019',
 '03683',
 '04595',
 '09460',
 '09998',
 '07490',
 '04882',
 '28107',
 '00646',
 '04768',
 '08629',
 '03843',
 '00132',
 '02161',
 '19441',
 '24669',
 '14385',
 '04501',
 '04295',
 '05050',
 '08818',
 '01258',
 '05850',
 '07442',
 '08450',
 '24196',
 '99963',
 '08745',
 '12137',
 '25833',
 '05593',
 '08682',
 '02246',
 '03203',
 '06274',
 '24369',
 '04757',
 '05901',
 '10243',
 '10746',
 '22686',
 '03852',
 '08258',
 '10696',
 '10984',
 '28679',
 '00862',
 '06783',
 '06955',
 '24473',
 '21750',
 '10066',
 '26994',
 '25825',
 '09075',
 '03223',
 '23596',
 '06913',
 '07848',
 '24988',
 '02153',
 '05536',
 '05651',
 '08550',
 '11677',
 '12168',
 '14131',
 '04897',
 '04943',
 '15271',
 '19525',
 '06574',
 '24000',
 '04746',
 '10102',
 '11014',
 '25105',
 '09969',
 '99931',
 '01554',
 '00909',
 '28680',
 '09173',
 '09216',
 '10771',
 '09176',
 '11306',
 '16923',
 '26968',
 '28746',
 '06555',
 '01018',
 '20202',
 '26998',
 '25615',
 '01612',
 '08793',
 '24395',
 '09130',
 '05306',
 '11964',
 '07357',
 '10952',
 '00322',
 '00635',
 '07147',
 '26310',
 '06199',
 '04207',
 '22826',
 '06372',
 '04460',
 '07023',
 '24153',
 '08893',
 '26297',
 '08319',
 '02312',
 '00559',
 '28225',
 '13738',
 '23984',
 '03429',
 '07007',
 '22129',
 '01271',
 '09061',
 '06838',
 '99874',
 '03540',
 '07011',
 '03996',
 '07656',
 '01187',
 '01214',
 '14218',
 '05113',
 '23020',
 '26724',
 '09339',
 '06593',
 '03476',
 '09921',
 '00794',
 '04939',
 '15733',
 '27407',
 '22818',
 '03702',
 '24085',
 '04885',
 '10947',
 '00527',
 '09310',
 '05766',
 '11072',
 '03048',
 '15108',
 '08434',
 '07766',
 '06977',
 '05990',
 '03430',
 '00449',
 '10701',
 '11838',
 '09666',
 '06276',
 '23904',
 '99743',
 '25807',
 '00153',
 '03902',
 '28043',
 '02968',
 '07510',
 '05784',
 '09235',
 '03921',
 '09441',
 '11495',
 '24416',
 '07892',
 '09849',
 '04398',
 '09033',
 '17295',
 '11592',
 '05447',
 '00393',
 '00965',
 '02302',
 '07575',
 '00439',
 '22774',
 '02170',
 '08033',
 '26898',
 '04639',
 '23955',
 '01606',
 '08655',
 '11715',
 '08804',
 '25842',
 '28199',
 '28340',
 '08777',
 '00166',
 '24544',
 '00002',
 '11850',
 '04738',
 '09031',
 '00921',
 '04458',
 '08896',
 '24010',
 ...}

In [139]:
data = dn_alldb_drop.merge(dn_hospital_drop,how='left',left_on='site',right_on='hcode')
data

,user,RowKey,date,phone,site,time,urine,ov,PartitionKey,hcode,name,zone_code,zone_name,provincecode,province,amphurcode,amphur,tamboncode,tambon
0,85879,shmpdrmtgc.png,2022-03-24,OPPO CPH2293,05194,13:08:39,มีตะกอน,0,0000,05194,โรงพยาบาลส่งเสริมสุขภาพตำบลบ้านหนองหว้า ตำบลกก...,7.0,สาขาพื้นที่(ขอนแก่น),45.0,ร้อยเอ็ด,9.0,หนองพอก,4.0,กกโพธิ์
1,45-161,D2CABB8C-533B-450A-AFA6-B693749CC1C6,2022-02-23,"iPhone11,8",04312,09:45:28,ปกติ (เหลืองใส),0,0-1528,04312,โรงพยาบาลส่งเสริมสุขภาพตำบลสีชมพู,7.0,สาขาพื้นที่(ขอนแก่น),40.0,ขอนแก่น,6.0,สีชมพู,1.0,สีชมพู
2,45-161,57A5F06C-C840-49EA-9514-A30D3C897CC8,2022-02-23,"iPhone11,8",04312,10:06:45,ปกติ (เหลืองใส),0,0-1544,04312,โรงพยาบาลส่งเสริมสุขภาพตำบลสีชมพู,7.0,สาขาพื้นที่(ขอนแก่น),40.0,ขอนแก่น,6.0,สีชมพู,1.0,สีชมพู
3,27529,ADC54E82-4225-4DE6-89A6-A7E556C15FB1,2022-02-25,"iPhone13,1",04999,14:22:22,ปกติ (เหลืองใส),0,0000,04999,โรงพยาบาลส่งเสริมสุขภาพตำบลบ้านเปลือย,7.0,สาขาพื้นที่(ขอนแก่น),44.0,มหาสารคาม,6.0,บรบือ,19.0,หนองโก
4,06223,kfpwuaqldj.png,2022-03-23,Xiaomi 21081111RG,13777,16:31:45,ปกติ (เหลืองใส),0,00000,13777,โรงพยาบาลศรีนครินทร์ มหาวิทยาลัยขอนแก่น,7.0,สาขาพื้นที่(ขอนแก่น),40.0,ขอนแก่น,1.0,เมืองขอนแก่น,1.0,ในเมือง
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38658,ttest,crqcufokmn.png,2022-02-21,Samsung SM-G998B,ไม่ระบุ,14:23:45,ขุ่น,2,x001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38659,ttest,gzxgflnowr.png,2022-02-21,Samsung SM-G998B,ไม่ระบุ,14:23:43,ขุ่น,2,x001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38660,xxx,jytlopevha.png,2022-02-17,Samsung SM-N950F,ไม่ระบุ,00:01:06,ปกติ (เหลืองใส),3,xxx,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38661,yyy,ivccsksowb.png,2022-02-17,Samsung SM-N950F,ไม่ระบุ,08:41:05,มีเม็ดเลือดแดง,2,yyy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38662,zzz,psudrnccsh.png,2022-02-17,Samsung SM-N950F,ไม่ระบุ,08:41:04,มีตะกอน,2,zzz,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [140]:
data.isnull().sum()

user              0
RowKey            0
date              0
phone             0
site              0
time              0
urine             0
ov                0
PartitionKey      0
hcode           379
name            379
zone_code       379
zone_name       379
provincecode    379
province        379
amphurcode      379
amphur          379
tamboncode      379
tambon          379
dtype: int64

In [141]:
drop_data = data.dropna()
drop_data

,user,RowKey,date,phone,site,time,urine,ov,PartitionKey,hcode,name,zone_code,zone_name,provincecode,province,amphurcode,amphur,tamboncode,tambon
0,85879,shmpdrmtgc.png,2022-03-24,OPPO CPH2293,05194,13:08:39,มีตะกอน,0,0000,05194,โรงพยาบาลส่งเสริมสุขภาพตำบลบ้านหนองหว้า ตำบลกก...,7.0,สาขาพื้นที่(ขอนแก่น),45.0,ร้อยเอ็ด,9.0,หนองพอก,4.0,กกโพธิ์
1,45-161,D2CABB8C-533B-450A-AFA6-B693749CC1C6,2022-02-23,"iPhone11,8",04312,09:45:28,ปกติ (เหลืองใส),0,0-1528,04312,โรงพยาบาลส่งเสริมสุขภาพตำบลสีชมพู,7.0,สาขาพื้นที่(ขอนแก่น),40.0,ขอนแก่น,6.0,สีชมพู,1.0,สีชมพู
2,45-161,57A5F06C-C840-49EA-9514-A30D3C897CC8,2022-02-23,"iPhone11,8",04312,10:06:45,ปกติ (เหลืองใส),0,0-1544,04312,โรงพยาบาลส่งเสริมสุขภาพตำบลสีชมพู,7.0,สาขาพื้นที่(ขอนแก่น),40.0,ขอนแก่น,6.0,สีชมพู,1.0,สีชมพู
3,27529,ADC54E82-4225-4DE6-89A6-A7E556C15FB1,2022-02-25,"iPhone13,1",04999,14:22:22,ปกติ (เหลืองใส),0,0000,04999,โรงพยาบาลส่งเสริมสุขภาพตำบลบ้านเปลือย,7.0,สาขาพื้นที่(ขอนแก่น),44.0,มหาสารคาม,6.0,บรบือ,19.0,หนองโก
4,06223,kfpwuaqldj.png,2022-03-23,Xiaomi 21081111RG,13777,16:31:45,ปกติ (เหลืองใส),0,00000,13777,โรงพยาบาลศรีนครินทร์ มหาวิทยาลัยขอนแก่น,7.0,สาขาพื้นที่(ขอนแก่น),40.0,ขอนแก่น,1.0,เมืองขอนแก่น,1.0,ในเมือง
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38562,76331,pvpiawlexb.png,2022-02-23,Samsung SM-G965U,05258,15:32:53,ปกติ (เหลืองใส),1,92,05258,โรงพยาบาลส่งเสริมสุขภาพตำบลหนองตาโฮม ตำบลขี้เหล็ก,7.0,สาขาพื้นที่(ขอนแก่น),45.0,ร้อยเอ็ด,14.0,อาจสามารถ,9.0,ขี้เหล็ก
38565,68317,rtutxrlbam.png,2022-02-23,Samsung SM-A115F,28017,14:31:01,ปกติ (เหลืองใส),2,976,28017,โรงพยาบาลนาคู,7.0,สาขาพื้นที่(ขอนแก่น),46.0,กาฬสินธุ์,16.0,นาคู,1.0,นาคู
38566,68317,dmuragqwza.png,2022-02-23,Samsung SM-A115F,28017,14:30:21,ปกติ (เหลืองใส),2,983,28017,โรงพยาบาลนาคู,7.0,สาขาพื้นที่(ขอนแก่น),46.0,กาฬสินธุ์,16.0,นาคู,1.0,นาคู
38569,68768,D8A3A9EA-929E-4CEB-BFDF-C9BE093EA663,2022-03-24,"iPhone11,8",11088,10:25:32,ปกติ (เหลืองใส),1,99444,11088,โรงพยาบาลห้วยผึ้ง,7.0,สาขาพื้นที่(ขอนแก่น),46.0,กาฬสินธุ์,14.0,ห้วยผึ้ง,3.0,นิคมห้วยผึ้ง
38570,99771,E04D3D60-B916-40A1-AE77-91CCD89DD084,2022-03-31,"iPhone10,5",05396,11:03:40,ปกติ (เหลืองใส),0,99771,05396,โรงพยาบาลส่งเสริมสุขภาพตำบลบ้านสูงเนิน,7.0,สาขาพื้นที่(ขอนแก่น),46.0,กาฬสินธุ์,10.0,คำม่วง,9.0,เนินยาง

In [142]:
removes = data.shape[0] - drop_data.shape[0]
print(f'size before drop = {data.shape[0]}')
print(f'size after drop = {drop_data.shape[0]}')
print(f'% from drop = {(removes/data.shape[0])*100}')

size before drop = 38663
size after drop = 38284
% from drop = 0.980265369991982

In [143]:
set(drop_data['user'])

{'92042',
 '19903',
 '50349',
 '00131',
 '75921',
 '48768',
 '00266',
 '19364',
 '73233',
 '23675',
 '46627',
 '00253',
 '96699',
 '18873',
 '78257',
 '00001',
 '52013',
 '46948',
 '27604',
 '71112',
 '38614',
 '17415',
 '71970',
 '00021',
 '45783',
 '53356',
 '43868',
 '21860',
 '02639',
 '81065',
 '55300',
 '72988',
 '70610',
 '58271',
 '84375',
 '75771',
 '19201',
 '03080',
 '5600190011969',
 '00206',
 '19578',
 '66261',
 '74369',
 '98126',
 '58845',
 '24563',
 '00017',
 '3460500500020',
 '61320',
 '18890',
 '00267',
 '70948',
 '70940',
 '49863',
 '34988',
 '00183',
 '47567',
 '05961',
 '48514',
 '78731',
 '28961',
 '00074',
 '55365',
 '24179',
 '00150',
 '29159',
 '48298',
 '77576',
 '12966',
 '35605',
 '56845',
 '54599',
 '00036',
 '96349',
 '69576',
 '99011',
 '00117',
 '87771',
 '28402',
 '14088',
 '00298',
 '76459',
 '72225',
 '08011',
 '00294',
 '79920',
 '00299',
 '23416',
 '07644',
 '02217',
 '00023',
 '00149',
 '00284',
 '95821',
 '37732',
 '3450101229373',
 '00281',
 '38381',
 '01403',
 '00165',
 '66082',
 '40591\n40591\n',
 '00127',
 '63200',
 '10982',
 '00034',
 '32873',
 '26511',
 '71891',
 '22545',
 '72938',
 '98171',
 '51653',
 '18008',
 '76088',
 '84392',
 '79834',
 '01008',
 '00014',
 '38121',
 '25083',
 '00211',
 '37914',
 '70059',
 '05211',
 '34331',
 '12413',
 '83303',
 '97770',
 '52219',
 '33643',
 '20061',
 '86601',
 '12576',
 '00226',
 '61087',
 '31062',
 '42173',
 '09269',
 '16970',
 '11055',
 '18402',
 '38771',
 '41937',
 '78494',
 '5799',
 '81293',
 '19671',
 '67972',
 '00076',
 '00209',
 '71378\n71378',
 '77572',
 '19800',
 '94392',
 '27902',
 '31577',
 '18318',
 '19855',
 '70490',
 '16971',
 '96061',
 '77726',
 '16820',
 '27732',
 '65254',
 '16085',
 '3450100940367',
 '67400',
 '96730',
 '91811',
 '05069',
 '19265',
 '59181',
 '01636',
 '88377',
 '31086',
 '62768',
 '00286',
 '27046',
 '59269',
 '00042',
 '13824',
 '11215',
 '71921',
 '20395',
 '00316',
 '63606',
 '74335',
 '45485',
 '00273',
 '27096',
 '95193',
 '65390',
 '51065',
 '78334',
 '22478',
 '46622',
 '00178',
 '00188',
 '19411',
 '61813',
 '18733',
 '00196',
 '00309',
 '35888',
 '92431',
 '77688',
 '  noknoi2601@gmail.com\n',
 '25219',
 '90154',
 '89470',
 '34791',
 '00624',
 '84493',
 '80067',
 '05291',
 '51060',
 '96670',
 '00755',
 '76299',
 '17536\n\n17536',
 '46767',
 '46520',
 '90612',
 '19211',
 '26776',
 '01651',
 '94150',
 '62941',
 '95291',
 '84768',
 '50276',
 '82685',
 '00018',
 '05368',
 '28992',
 '51403',
 '86588',
 '32625',
 '00035',
 '73225',
 '83257',
 '45047',
 '00032',
 '55911',
 '44812',
 '04347',
 '63274',
 '92415',
 '73038',
 '02128',
 '46285',
 '90872',
 '64810',
 '55806',
 '47429',
 '31208',
 '28399',
 '74289',
 '47615',
 '00208',
 '00233',
 '37216',
 '19875',
 '00123',
 '72451',
 '95301',
 '50951',
 '87802',
 '36141',
 '00910',
 '77567',
 '82582',
 '17790',
 '03663',
 '49961',
 '00342',
 '00187',
 '06316',
 '9250',
 '03217',
 '10993',
 '11111111',
 '06277',
 '46902',
 '06079',
 '04281',
 '3450100810285',
 '66501',
 '52678',
 '76331',
 '04854',
 '26957',
 '33100',
 '09188',
 '13312',
 '18524',
 '74338',
 '77384',
 '45161',
 '00169',
 '67212',
 '69428',
 '46291',
 '3450101576642',
 '45641',
 '04388',
 '93189',
 '02087',
 '34705',
 '00071',
 '00203',
 '51301',
 '33103',
 '00200',
 '85504',
 '00201',
 '00582',
 '03558',
 '11159',
 '65775',
 '01431',
 '52665',
 '19624',
 '31551',
 '31619',
 '06655',
 '69037',
 '17938',
 '16193',
 '00118',
 '00024',
 '32949',
 '00308',
 '17777',
 '98829',
 '00404',
 '21688',
 '00214',
 '00312',
 '91125',
 '47494',
 '22119',
 '00221',
 '19130',
 '05232',
 '55299',
 '00168',
 '23554',
 '52922',
 '88315',
 '00307',
 '99991',
 '16162',
 '29118',
 '24468',
 '86113',
 '17184',
 '94494',
 '00277',
 '18737',
 '79525',
 '39802',
 '49308',
 '00132',
 '28381',
 '54761',
 '12786',
 '83900',
 '97965',
 '44888',
 '08818',
 '00748',
 '33503',
 '91438',
 '49413',
 '66801',
 '14667',
 '00163',
 '22688',
 '23596',
 '05590',
 '77782',
 '95104',
 '39440',
 '15588',
 '97016',
 '52350',
 '14106',
 '60181',
 '74367',
 '3451100146637',
 '90604',
 '00285',
 '64385',
 '00322',
 '43791',
 '61587',
 '90070',
 '46662',
 '3459900286317',
 '00320',
 '85444',
 '94454',
 '12605',
 '19002',
 '3450101325593',
 '36358',
 '05113',
 '00025',
 '00197',
 '05047',
 '21955',
 '00287',
 '86774',
 '00153',
 '24375',
 '28743',
 '16112',
 '04461',
 '22722',
 '00088',
 '18331',
 '82894',
 '97290',
 '29000',
 '55415',
 '09820',
 '31322',
 '53076',
 '08777',
 '00166',
 '62061',
 '00002',
 '19699',
 '16754',
 '10120',
 '95978',
 '00902',
 '14360',
 '36481',
 '63429',
 '44018',
 '10518',
 '87315',
 '58870',
 '88351',
 '23958',
 '19241',
 '20606',
 '01408',
 '39965',
 '28627',
 '80317',
 '69789',
 '03100',
 '64503',
 '5450100026807',
 '35512',
 '68112',
 '08734',
 '08602',
 '63767',
 '02784',
 '60250',
 '03617',
 '45736',
 '80734',
 '63865',
 '64671',
 '53751',
 '17966',
 '32200',
 '89329',
 '41042',
 '49161',
 '00274',
 '26916',
 '49215',
 '51039',
 '46970',
 '75251',
 '58668',
 '26647',
 '90888',
 '84494',
 '93726',
 '08773',
 '49880',
 '77862',
 '02647',
 '83771',
 '21177',
 '00112',
 '61591',
 '97484',
 '63312',
 '74964',
 '68037',
 '23889',
 '63018',
 '00006',
 '49241',
 '46333',
 '67850',
 '27678',
 '00090',
 '93028',
 '51903',
 '05019',
 '98080',
 '30977',
 '32077',
 '00037',
 '77665',
 '15737',
 '16848',
 '29379',
 '56051',
 '00343',
 '17842',
 '46897',
 '11522',
 '00194',
 '31401',
 '54192',
 '10673',
 '15734',
 '32666',
 '61359',
 '50172',
 '00272',
 '53943',
 '19675',
 '00020',
 '45924',
 '54427',
 '45881',
 '66155',
 '00170',
 '02878',
 '47122',
 '59476',
 '12378',
 '12561',
 '37186',
 '00073',
 '43143',
 '84063',
 '00235',
 '39764',
 '67352',
 '05304',
 '00129',
 '39959',
 '29094',
 '00054',
 '31114',
 '18527',
 '10653',
 '41026',
 '98530',
 '29309',
 '86133',
 '47933',
 '34096',
 '76339',
 '34585',
 '10194',
 '91947',
 '63748',
 '00328',
 '17132',
 '11198',
 '76105',
 '03500',
 '76819',
 '37915',
 '00065',
 '94601',
 '26043',
 '06964',
 '57228',
 '76246',
 '81529',
 '17974',
 '59361',
 '46341',
 '39448',
 '63381',
 '37140',
 '66473',
 '63837',
 '22244',
 '65555',
 '84276',
 '47623',
 '79001',
 '00121',
 '17564',
 '22692',
 '42465',
 '41061',
 '91209',
 '64817',
 '96771',
 '34501009308',
 '00167',
 '37259',
 '54538',
 '31755',
 '55547',
 '12044',
 '49782',
 '30481',
 '80847',
 '32082',
 '32948',
 '84540',
 '61605',
 '38463',
 '74747',
 '25781',
 '39342',
 '00155',
 '27589',
 '47950',
 '50466',
 '72186',
 '59144',
 '10348',
 '00043',
 '77670',
 '00283',
 '52921',
 '85702',
 '00009',
 '99835',
 '22455',
 '89681',
 '47157',
 '37228',
 '04483',
 '02962',
 '30041',
 '14884',
 '50756',
 '87181',
 '93991',
 '65656',
 '62415',
 '47607',
 '22099',
 '00081',
 '29441',
 '54923',
 '88942',
 '00207',
 '86542',
 '87541',
 '11808',
 '92545',
 '00052',
 '00210',
 '04402',
 '76642',
 '7140',
 '3451100150251',
 '22824',
 '41182',
 '32591',
 '29760',
 '22542',
 '88708',
 '63098',
 '51501',
 '31534',
 '42120',
 '05063',
 '68856',
 '51310',
 '74345',
 '57066',
 '19756',
 '79028',
 '85493',
 '42370',
 '87374',
 '00126',
 '00276',
 '47858',
 '05135',
 '49322',
 '63799',
 '00172',
 '67094',
 '72330',
 '94881',
 '31283',
 '49268',
 '02263',
 '00008',
 '53980',
 '3450101536268',
 '89290',
 '03421',
 '44364',
 '77743',
 '26459',
 '02913',
 '94758',
 '92648',
 '55692',
 '54214',
 '25478',
 '20304',
 '95609',
 '76523',
 '02471',
 '11742',
 '85737',
 '00177',
 '02579',
 '3451100451758',
 '00011',
 '96099',
 '90817',
 '86299',
 '70973',
 '73000',
 '62962',
 '67864',
 '75347',
 '82054',
 '79493',
 '00292',
 '99992',
 '96292',
 '48710',
 '63091',
 '00224',
 '38305',
 '62261',
 '95161',
 '21378',
 '89056',
 '02102',
 '15229',
 '65733',
 '90257',
 '90343',
 '25923',
 '76386',
 '86483',
 '37607',
 '00565',
 '26199',
 '15930',
 '16725',
 '3451400598487',
 '83733',
 '03953',
 '74782',
 '61325',
 '37249',
 '05210',
 '89081',
 '20215',
 '59266',
 '73419',
 '00108',
 '33739',
 '00317',
 '3450101325119',
 '73336',
 '33081',
 '11361',
 '3400900747146',
 '79620',
 '98245',
 '94988',
 '82954',
 '29999',
 '26779',
 '00158',
 '00040',
 '42453',
 '11387',
 '03338',
 '83937',
 '94087',
 '59305',
 '00217',
 '05116',
 '7197',
 '01183',
 '35139',
 '03731',
 '745-61',
 '66062',
 '02594',
 '56326',
 '15678',
 '13070',
 '3',
 '87029',
 '51973',
 '00190',
 '19737',
 '12003',
 '52131',
 '00007',
 '61552',
 '99475',
 '71378',
 '31143',
 '49367',
 '63852',
 '48069',
 '31811',
 '96706',
 '86271',
 '06924',
 '88337',
 '81537',
 '97913',
 '26989',
 '62616',
 '00053',
 '50047',
 '14037',
 '10264',
 '83276',
 '41951',
 '26440',
 '86758',
 '30059',
 '29025',
 '30431',
 '98290',
 '78054',
 '00010',
 '80374',
 '00202',
 '70054',
 '00263',
 '00151',
 '08242',
 '48440',
 '67379',
 '34829',
 '75841',
 '37018',
 '00269',
 '65678',
 '60147',
 '25176',
 '89475',
 '83377',
 '23796',
 '00038',
 '00204',
 '75126',
 '94538',
 '44201',
 '01883',
 '5451100055352',
 '43657',
 '98703',
 '16144',
 '06681',
 '89609',
 '00173',
 '00215',
 '18892',
 '03381',
 '18041',
 '14189',
 '74493',
 '66771',
 '34210',
 '3450100805222',
 '23214',
 '44199',
 '64520',
 '47354',
 '30511',
 '87738',
 '27129',
 '02897',
 '25837',
 '00566',
 '95668',
 '46566',
 '08741',
 '11111',
 '00148',
 '72169',
 '19920',
 '05091',
 '63306',
 '46775',
 '42380',
 '87394',
 '92580',
 '25659',
 '77509',
 '58196',
 '90516',
 '44845',
 '45846',
 '28186',
 '49387',
 '61746',
 '61486',
 '07427',
 '60688',
 '64081',
 '82822',
 '31196',
 '30016',
 '27658',
 '89913',
 '54544',
 '28977',
 '49103',
 '03649',
 '51205',
 '90770',
 '86981',
 '59051',
 '05082',
 '29417',
 '47605',
 '00124',
 '43068',
 '00353',
 '00139',
 '16284',
 '31229',
 '80481',
 '71998',
 '45729',
 '28062',
 '68162',
 '55865',
 '71503',
 '00399',
 '03431',
 '00348',
 '86721',
 '28241',
 '98474',
 '48908',
 '00141',
 '89251',
 '54734',
 '78673',
 '12723',
 '52210',
 '50284',
 '51892',
 '22804',
 '74951',
 '47146',
 '09902',
 '49659',
 '41301',
 '37728',
 '07331',
 '87536',
 '36692',
 '98519',
 '72486',
 '48393',
 '96417',
 '53188',
 '38422',
 '36001',
 '70810',
 '00031',
 '95927',
 '63284',
 '54974',
 '00161',
 '3451100451251',
 '87337',
 '71152',
 '00304',
 '22377',
 '10695',
 '04221',
 '29514',
 '89801',
 '26574',
 '08072',
 '00216',
 '30283',
 '77358',
 ...}

In [144]:
drop_data['user'].replace({'3451100150251':'ไม่ระบุ',
                            '3451100324713':'ไม่ระบุ',
                            '3450500541443':'ไม่ระบุ',
                            '3451100141252':'ไม่ระบุ',
                            '3451100324624':'ไม่ระบุ',
                            '3459900286317':'ไม่ระบุ',
                            '5450100026807':'ไม่ระบุ',
                            '7140':'ไม่ระบุ',
                            '3450101229373':'ไม่ระบุ',
                            '3450101556129':'ไม่ระบุ',
                            '3450100836420':'ไม่ระบุ',
                            '3451100146637':'ไม่ระบุ',
                            '17536\n\n17536':'ไม่ระบุ',
                            '5451100055352':'ไม่ระบุ',
                            '7197':'ไม่ระบุ',
                            '3450100940367':'ไม่ระบุ',
                            '11111111':'ไม่ระบุ',
                            '  67241\n':'67241',
                            '3450101325119':'ไม่ระบุ',
                            'ttohn':'ไม่ระบุ',
                            '45-161':'45161'}, inplace=True)

/usr/local/lib/python3.7/dist-packages/pandas/core/generic.py:6619: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return self._update_inplace(result)

In [145]:
set(drop_data['user'])

{'92042',
 '19903',
 '50349',
 '00131',
 '75921',
 '48768',
 '00266',
 '19364',
 '73233',
 '23675',
 '46627',
 '00253',
 '96699',
 '18873',
 '78257',
 '00001',
 '52013',
 '46948',
 '27604',
 '71112',
 '38614',
 '17415',
 '71970',
 '00021',
 '45783',
 '53356',
 '43868',
 '21860',
 '02639',
 '81065',
 '55300',
 '72988',
 '70610',
 '58271',
 '84375',
 '75771',
 '19201',
 '03080',
 '5600190011969',
 '00206',
 '19578',
 '66261',
 '74369',
 '98126',
 '58845',
 '24563',
 '00017',
 '3460500500020',
 '61320',
 '18890',
 '00267',
 '70948',
 '70940',
 '49863',
 '34988',
 '00183',
 '47567',
 '05961',
 '48514',
 '78731',
 '28961',
 '00074',
 '55365',
 '24179',
 '00150',
 '29159',
 '48298',
 '77576',
 '12966',
 '35605',
 '56845',
 '54599',
 '00036',
 '96349',
 '69576',
 '99011',
 '00117',
 '87771',
 '28402',
 '14088',
 '00298',
 '76459',
 '72225',
 '08011',
 '00294',
 '79920',
 '00299',
 '23416',
 '07644',
 '02217',
 '00023',
 '00149',
 '00284',
 '95821',
 '37732',
 '00281',
 '38381',
 '01403',
 '00165',
 '66082',
 '40591\n40591\n',
 '00127',
 '63200',
 '10982',
 '00034',
 '32873',
 '26511',
 '71891',
 '22545',
 '72938',
 '98171',
 '51653',
 '18008',
 '76088',
 '84392',
 '79834',
 '01008',
 '00014',
 '38121',
 '25083',
 '00211',
 '37914',
 '70059',
 '05211',
 '34331',
 '12413',
 '83303',
 '97770',
 '52219',
 '33643',
 '20061',
 '86601',
 '12576',
 '00226',
 '61087',
 '31062',
 '42173',
 '09269',
 '16970',
 '11055',
 '18402',
 '38771',
 '41937',
 '78494',
 '5799',
 '81293',
 '19671',
 '67972',
 '00076',
 '00209',
 '71378\n71378',
 '77572',
 '19800',
 '94392',
 '27902',
 '31577',
 '18318',
 '19855',
 '70490',
 '16971',
 '96061',
 '77726',
 '16820',
 '27732',
 '65254',
 '16085',
 '67400',
 '96730',
 '91811',
 '05069',
 '19265',
 '59181',
 '01636',
 '88377',
 '31086',
 '62768',
 '00286',
 '27046',
 '59269',
 '00042',
 '13824',
 '11215',
 '71921',
 '20395',
 '00316',
 '63606',
 '74335',
 '45485',
 '00273',
 '27096',
 '95193',
 '65390',
 '51065',
 '78334',
 '22478',
 '46622',
 '00178',
 '00188',
 '19411',
 '61813',
 '18733',
 '00196',
 '00309',
 '35888',
 '92431',
 '77688',
 '  noknoi2601@gmail.com\n',
 '25219',
 '90154',
 '89470',
 '34791',
 '00624',
 '84493',
 '80067',
 '05291',
 '51060',
 '96670',
 '00755',
 '76299',
 '46767',
 '46520',
 '90612',
 '19211',
 '26776',
 '01651',
 '94150',
 '62941',
 '95291',
 '84768',
 '50276',
 '82685',
 '00018',
 '05368',
 '28992',
 '51403',
 '86588',
 '32625',
 '00035',
 '73225',
 '83257',
 '45047',
 '00032',
 '55911',
 '44812',
 '04347',
 '63274',
 '92415',
 '73038',
 '02128',
 '46285',
 '90872',
 '64810',
 '55806',
 '47429',
 '31208',
 '28399',
 '74289',
 '47615',
 '00208',
 '00233',
 '37216',
 '19875',
 '00123',
 '72451',
 '95301',
 '50951',
 '87802',
 '36141',
 '00910',
 '77567',
 '82582',
 '17790',
 '03663',
 '49961',
 '00342',
 '00187',
 '06316',
 '9250',
 '03217',
 '10993',
 '06277',
 '46902',
 '06079',
 '04281',
 '3450100810285',
 '66501',
 '52678',
 '76331',
 '04854',
 '26957',
 '33100',
 '09188',
 '13312',
 '18524',
 '74338',
 '77384',
 '45161',
 '00169',
 '67212',
 '69428',
 '46291',
 '3450101576642',
 '45641',
 '04388',
 '93189',
 '02087',
 '34705',
 '00071',
 '00203',
 '51301',
 '33103',
 '00200',
 '85504',
 '00201',
 '00582',
 '03558',
 '11159',
 '65775',
 '01431',
 '52665',
 '19624',
 '31551',
 '31619',
 '06655',
 '69037',
 '17938',
 '16193',
 '00118',
 '00024',
 '32949',
 '00308',
 '17777',
 '98829',
 '00404',
 '21688',
 '00214',
 '00312',
 '91125',
 '47494',
 '22119',
 '00221',
 '19130',
 '05232',
 '55299',
 '00168',
 '23554',
 '52922',
 '88315',
 '00307',
 '99991',
 '16162',
 '29118',
 '24468',
 '86113',
 '17184',
 '94494',
 '00277',
 '18737',
 '79525',
 '39802',
 '49308',
 '00132',
 '28381',
 '54761',
 '12786',
 '83900',
 '97965',
 '44888',
 '08818',
 '00748',
 '33503',
 '91438',
 '49413',
 '66801',
 '14667',
 '00163',
 '22688',
 '23596',
 '05590',
 '77782',
 '95104',
 '39440',
 '15588',
 '97016',
 '52350',
 '14106',
 '60181',
 '74367',
 '90604',
 '00285',
 '64385',
 '00322',
 '43791',
 '61587',
 '90070',
 '46662',
 '00320',
 '85444',
 '94454',
 '12605',
 '19002',
 '3450101325593',
 '36358',
 '05113',
 '00025',
 '00197',
 '05047',
 '21955',
 '00287',
 '86774',
 '00153',
 '24375',
 '28743',
 '16112',
 '04461',
 '22722',
 '00088',
 '18331',
 '82894',
 '97290',
 '29000',
 '55415',
 '09820',
 '31322',
 '53076',
 '08777',
 '00166',
 '62061',
 '00002',
 '19699',
 '16754',
 '10120',
 '95978',
 '00902',
 '14360',
 '36481',
 '63429',
 '44018',
 '10518',
 '87315',
 '58870',
 '88351',
 '23958',
 '19241',
 '20606',
 '01408',
 '39965',
 '28627',
 '80317',
 '69789',
 '03100',
 '64503',
 '35512',
 '68112',
 '08734',
 '08602',
 '63767',
 '02784',
 '60250',
 '03617',
 '45736',
 '80734',
 '63865',
 '64671',
 '53751',
 '17966',
 '32200',
 '89329',
 '41042',
 '49161',
 '00274',
 '26916',
 '49215',
 '51039',
 '46970',
 '75251',
 '58668',
 '26647',
 '90888',
 '84494',
 '93726',
 '08773',
 '49880',
 '77862',
 '02647',
 '83771',
 '21177',
 '00112',
 '61591',
 '97484',
 '63312',
 '74964',
 '68037',
 '23889',
 '63018',
 '00006',
 '49241',
 '46333',
 '67850',
 '27678',
 '00090',
 '93028',
 '51903',
 '05019',
 '98080',
 '30977',
 '32077',
 '00037',
 '77665',
 '15737',
 '16848',
 '29379',
 '56051',
 '00343',
 '17842',
 '46897',
 '11522',
 '00194',
 '31401',
 '54192',
 '10673',
 '15734',
 '32666',
 '61359',
 '50172',
 '00272',
 '53943',
 '19675',
 '00020',
 '45924',
 '54427',
 '45881',
 '66155',
 '00170',
 '02878',
 '47122',
 '59476',
 '12378',
 '12561',
 '37186',
 '00073',
 '43143',
 '84063',
 '00235',
 '39764',
 '67352',
 '05304',
 '00129',
 '39959',
 '29094',
 '00054',
 '31114',
 '18527',
 '10653',
 '41026',
 '98530',
 '29309',
 '86133',
 '47933',
 '34096',
 '76339',
 '34585',
 '10194',
 '91947',
 '63748',
 '00328',
 '17132',
 '11198',
 '76105',
 '03500',
 '76819',
 '37915',
 '00065',
 '94601',
 '26043',
 '06964',
 '57228',
 '76246',
 '81529',
 '17974',
 '59361',
 '46341',
 '39448',
 '63381',
 '37140',
 '66473',
 '63837',
 '22244',
 '65555',
 '84276',
 '47623',
 '79001',
 '00121',
 '17564',
 '22692',
 '42465',
 '41061',
 '91209',
 '64817',
 '96771',
 '34501009308',
 '00167',
 '37259',
 '54538',
 '31755',
 '55547',
 '12044',
 '49782',
 '30481',
 '80847',
 '32082',
 '32948',
 '84540',
 '61605',
 '38463',
 '74747',
 '25781',
 '39342',
 '00155',
 '27589',
 '47950',
 '50466',
 '72186',
 '59144',
 '10348',
 '00043',
 '77670',
 '00283',
 '52921',
 '85702',
 '00009',
 '99835',
 '22455',
 '89681',
 '47157',
 '37228',
 '04483',
 '02962',
 '30041',
 '14884',
 '50756',
 '87181',
 '93991',
 '65656',
 '62415',
 '47607',
 '22099',
 '00081',
 '29441',
 '54923',
 '88942',
 '00207',
 '86542',
 '87541',
 '11808',
 '92545',
 '00052',
 '00210',
 '04402',
 '76642',
 '22824',
 '41182',
 '32591',
 '29760',
 '22542',
 '88708',
 '63098',
 '51501',
 '31534',
 '42120',
 '05063',
 '68856',
 '51310',
 '74345',
 '57066',
 '19756',
 '79028',
 '85493',
 '42370',
 '87374',
 '00126',
 '00276',
 '47858',
 '05135',
 '49322',
 '63799',
 '00172',
 '67094',
 '72330',
 '94881',
 '31283',
 '49268',
 '02263',
 '00008',
 '53980',
 '3450101536268',
 '89290',
 '03421',
 '44364',
 '77743',
 '26459',
 '02913',
 '94758',
 '92648',
 '55692',
 '54214',
 '25478',
 '20304',
 '95609',
 '76523',
 '02471',
 '11742',
 '85737',
 '00177',
 '02579',
 '3451100451758',
 '00011',
 '96099',
 '90817',
 '86299',
 '70973',
 '73000',
 '62962',
 '67864',
 '75347',
 '82054',
 '79493',
 '00292',
 '99992',
 '96292',
 '48710',
 '63091',
 '00224',
 '38305',
 '62261',
 '95161',
 '21378',
 '89056',
 '02102',
 '15229',
 '65733',
 '90257',
 '90343',
 '25923',
 '76386',
 '86483',
 '37607',
 '00565',
 '26199',
 '15930',
 '16725',
 '3451400598487',
 '83733',
 '03953',
 '74782',
 '61325',
 '37249',
 '05210',
 '89081',
 '20215',
 '59266',
 '73419',
 '00108',
 '33739',
 '00317',
 '73336',
 '33081',
 '11361',
 '3400900747146',
 '79620',
 '98245',
 '94988',
 '82954',
 '29999',
 '26779',
 '00158',
 '00040',
 '42453',
 '11387',
 '03338',
 '83937',
 '94087',
 '59305',
 '00217',
 '05116',
 '01183',
 '35139',
 '03731',
 '745-61',
 '66062',
 '02594',
 '56326',
 '15678',
 '13070',
 '3',
 '87029',
 '51973',
 '00190',
 '19737',
 '12003',
 '52131',
 '00007',
 '61552',
 '99475',
 '71378',
 '31143',
 '49367',
 '63852',
 '48069',
 '31811',
 '96706',
 '86271',
 '06924',
 '88337',
 '81537',
 '97913',
 '26989',
 '62616',
 '00053',
 '50047',
 '14037',
 '10264',
 '83276',
 '41951',
 '26440',
 '86758',
 '30059',
 '29025',
 '30431',
 '98290',
 '78054',
 '00010',
 '80374',
 '00202',
 '70054',
 '00263',
 '00151',
 '08242',
 '48440',
 '67379',
 '34829',
 '75841',
 '37018',
 '00269',
 '65678',
 '60147',
 '25176',
 '89475',
 '83377',
 '23796',
 '00038',
 '00204',
 '75126',
 '94538',
 '44201',
 '01883',
 '43657',
 '98703',
 '16144',
 '06681',
 '89609',
 '00173',
 '00215',
 '18892',
 '03381',
 '18041',
 '14189',
 '74493',
 '66771',
 '34210',
 '3450100805222',
 '23214',
 '44199',
 '64520',
 '47354',
 '30511',
 '87738',
 '27129',
 '02897',
 '25837',
 '00566',
 '95668',
 '46566',
 '08741',
 '11111',
 '00148',
 '72169',
 '19920',
 '05091',
 '63306',
 '46775',
 '42380',
 '87394',
 '92580',
 '25659',
 '77509',
 '58196',
 '90516',
 '44845',
 '45846',
 '28186',
 '49387',
 '61746',
 '61486',
 '07427',
 '60688',
 '64081',
 '82822',
 '31196',
 '30016',
 '27658',
 '89913',
 '54544',
 '28977',
 '49103',
 '03649',
 '51205',
 '90770',
 '86981',
 '59051',
 '05082',
 '29417',
 '47605',
 '00124',
 '43068',
 '00353',
 '00139',
 '16284',
 '31229',
 '80481',
 '71998',
 '45729',
 '28062',
 '68162',
 '55865',
 '71503',
 '00399',
 '03431',
 '00348',
 '86721',
 '28241',
 '98474',
 '48908',
 '00141',
 '89251',
 '54734',
 '78673',
 '12723',
 '52210',
 '50284',
 '51892',
 '22804',
 '74951',
 '47146',
 '09902',
 '49659',
 '41301',
 '37728',
 '07331',
 '87536',
 '36692',
 '98519',
 '72486',
 '48393',
 '96417',
 '53188',
 '38422',
 '36001',
 '70810',
 '00031',
 '95927',
 '63284',
 '54974',
 '00161',
 '3451100451251',
 '87337',
 '71152',
 '00304',
 '22377',
 '10695',
 '04221',
 '29514',
 '89801',
 '26574',
 '08072',
 '00216',
 '30283',
 '77358',
 '00030',
 '41340',
 '00047',
 '14891',
 '73557',
 '05974',
 '51175',
 '55236',
 '15980',
 '00078',
 '78486',
 '55239',
 ...}

In [146]:
type('RowKey')

str

In [147]:
drop_data['date'] = pd.to_datetime(drop_data['date'],format="%Y/%m/%d") # เปลี่ยน format ของข้อมูลวันที่ให้อยู่ในรูปแบบเดียวกัน
drop_data[['date']]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

            date
0     2022-03-24
1     2022-02-23
2     2022-02-23
3     2022-02-25
4     2022-03-23
...          ...
38562 2022-02-23
38565 2022-02-23
38566 2022-02-23
38569 2022-03-24
38570 2022-03-31

[38284 rows x 1 columns]

In [148]:
type('Phone')

str

In [149]:
type('urine')

str

In [150]:
from datetime import datetime

In [151]:
from datetime import timedelta

In [152]:
drop_data['time'] = pd.to_timedelta(drop_data['time'],format = "%H:%M:%S") # เปลี่ยน format ของข้อมูลวันที่ให้อยู่ในรูปแบบเดียวกัน
drop_data[['time']]

TypeError: ignored

In [153]:
drop_data

,user,RowKey,date,phone,site,time,urine,ov,PartitionKey,hcode,name,zone_code,zone_name,provincecode,province,amphurcode,amphur,tamboncode,tambon
0,85879,shmpdrmtgc.png,2022-03-24,OPPO CPH2293,05194,13:08:39,มีตะกอน,0,0000,05194,โรงพยาบาลส่งเสริมสุขภาพตำบลบ้านหนองหว้า ตำบลกก...,7.0,สาขาพื้นที่(ขอนแก่น),45.0,ร้อยเอ็ด,9.0,หนองพอก,4.0,กกโพธิ์
1,45161,D2CABB8C-533B-450A-AFA6-B693749CC1C6,2022-02-23,"iPhone11,8",04312,09:45:28,ปกติ (เหลืองใส),0,0-1528,04312,โรงพยาบาลส่งเสริมสุขภาพตำบลสีชมพู,7.0,สาขาพื้นที่(ขอนแก่น),40.0,ขอนแก่น,6.0,สีชมพู,1.0,สีชมพู
2,45161,57A5F06C-C840-49EA-9514-A30D3C897CC8,2022-02-23,"iPhone11,8",04312,10:06:45,ปกติ (เหลืองใส),0,0-1544,04312,โรงพยาบาลส่งเสริมสุขภาพตำบลสีชมพู,7.0,สาขาพื้นที่(ขอนแก่น),40.0,ขอนแก่น,6.0,สีชมพู,1.0,สีชมพู
3,27529,ADC54E82-4225-4DE6-89A6-A7E556C15FB1,2022-02-25,"iPhone13,1",04999,14:22:22,ปกติ (เหลืองใส),0,0000,04999,โรงพยาบาลส่งเสริมสุขภาพตำบลบ้านเปลือย,7.0,สาขาพื้นที่(ขอนแก่น),44.0,มหาสารคาม,6.0,บรบือ,19.0,หนองโก
4,06223,kfpwuaqldj.png,2022-03-23,Xiaomi 21081111RG,13777,16:31:45,ปกติ (เหลืองใส),0,00000,13777,โรงพยาบาลศรีนครินทร์ มหาวิทยาลัยขอนแก่น,7.0,สาขาพื้นที่(ขอนแก่น),40.0,ขอนแก่น,1.0,เมืองขอนแก่น,1.0,ในเมือง
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38562,76331,pvpiawlexb.png,2022-02-23,Samsung SM-G965U,05258,15:32:53,ปกติ (เหลืองใส),1,92,05258,โรงพยาบาลส่งเสริมสุขภาพตำบลหนองตาโฮม ตำบลขี้เหล็ก,7.0,สาขาพื้นที่(ขอนแก่น),45.0,ร้อยเอ็ด,14.0,อาจสามารถ,9.0,ขี้เหล็ก
38565,68317,rtutxrlbam.png,2022-02-23,Samsung SM-A115F,28017,14:31:01,ปกติ (เหลืองใส),2,976,28017,โรงพยาบาลนาคู,7.0,สาขาพื้นที่(ขอนแก่น),46.0,กาฬสินธุ์,16.0,นาคู,1.0,นาคู
38566,68317,dmuragqwza.png,2022-02-23,Samsung SM-A115F,28017,14:30:21,ปกติ (เหลืองใส),2,983,28017,โรงพยาบาลนาคู,7.0,สาขาพื้นที่(ขอนแก่น),46.0,กาฬสินธุ์,16.0,นาคู,1.0,นาคู
38569,68768,D8A3A9EA-929E-4CEB-BFDF-C9BE093EA663,2022-03-24,"iPhone11,8",11088,10:25:32,ปกติ (เหลืองใส),1,99444,11088,โรงพยาบาลห้วยผึ้ง,7.0,สาขาพื้นที่(ขอนแก่น),46.0,กาฬสินธุ์,14.0,ห้วยผึ้ง,3.0,นิคมห้วยผึ้ง
38570,99771,E04D3D60-B916-40A1-AE77-91CCD89DD084,2022-03-31,"iPhone10,5",05396,11:03:40,ปกติ (เหลืองใส),0,99771,05396,โรงพยาบาลส่งเสริมสุขภาพตำบลบ้านสูงเนิน,7.0,สาขาพื้นที่(ขอนแก่น),46.0,กาฬสินธุ์,10.0,คำม่วง,9.0,เนินยาง

In [154]:
set(drop_data['ov'])

{'0',
 '1',
 '2',
 '3',
 '4',
 'ติดเชื้อ +2 ',
 'มีตะกอน',
 'มีเม็ดเลือดแดง',
 'สีฟ้า หรือน้ำเงิน',
 'ใสเป็นน้ำเปล่า'}

In [155]:
drop_data['ov'].replace({'ติดเชื้อ +2 ':'ไม่ระบุ',
                            'มีตะกอน':'ไม่ระบุ',
                            'มีเม็ดเลือดแดง':'ไม่ระบุ',
                            'สีฟ้า หรือน้ำเงิน':'ไม่ระบุ',
                            'ใสเป็นน้ำเปล่า':'ไม่ระบุ',}, inplace=True)

/usr/local/lib/python3.7/dist-packages/pandas/core/generic.py:6619: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return self._update_inplace(result)

In [156]:
set(drop_data['ov'])

{'0', '1', '2', '3', '4', 'ไม่ระบุ'}

In [157]:
set(drop_data['PartitionKey'])

{'05994',
 '00632',
 '04626',
 '01437',
 '20044',
 '02624',
 '02919',
 '01261',
 '02763',
 '03362',
 '02730',
 '01948',
 '01439',
 '03552',
 '00131',
 '01064',
 '00779',
 '01926',
 '09040',
 '04014',
 '00266',
 '01712',
 '03932',
 '01232',
 '00253',
 '08914',
 '00332',
 '00592',
 '00546',
 '01920',
 '00001',
 '05223',
 '01583',
 '02672',
 '03383',
 '03472',
 '04753',
 '02686',
 '00021',
 '01172',
 '01362',
 '03980',
 '00458',
 '05259',
 '05342',
 '04680',
 '02752',
 '00567',
 '05831',
 '01696',
 '02997',
 '02484',
 '02639',
 '03311',
 '01047',
 '03378',
 '01322',
 '218',
 '02749',
 '01603',
 '00573',
 '05209',
 '00860',
 '02580',
 '01716',
 '02370',
 '01106',
 '04736',
 '02989',
 '00901',
 '03112',
 '01961',
 '00206',
 '01812',
 '01355',
 '04137',
 '00661',
 '05280',
 '00710',
 '01061',
 '01128',
 '01629',
 '01849',
 '00017',
 '00843',
 '03056',
 '08962',
 '00267',
 '00586',
 '00484',
 '00986',
 '01041',
 '00183',
 '03826',
 '02992',
 '05961',
 '00426',
 '01736',
 '00549',
 '01250',
 '16',
 '02824',
 '02066',
 '90470',
 '01252',
 '01452',
 '03509',
 '04187',
 '06262',
 '00074',
 '00150',
 '00461',
 '01350',
 '01737',
 '01123',
 '02470',
 '02803',
 '01444',
 '00798',
 '01373',
 '00036',
 '124',
 '00593',
 '00087',
 '00806',
 '02485',
 '05119',
 '00072',
 '00519',
 '02063',
 '02561',
 '03433',
 '00117',
 '01999',
 '00795',
 '01179',
 '02610',
 '00752',
 '01482',
 '01215',
 '01671',
 '00298',
 '02856',
 '00507',
 '01464',
 '01491',
 '00796',
 '03158',
 '01851',
 '09012',
 '02727',
 '02272',
 '01226',
 '01655',
 '00294',
 '01196',
 '03291',
 '05099',
 '00299',
 '03408',
 '00899',
 '08254',
 '01402',
 '02483',
 '02900',
 '00247',
 '23416',
 '01162',
 '00542',
 '01996',
 '00023',
 '00149',
 '08995',
 '179',
 '00284',
 '04253',
 '01607',
 '00281',
 '01403',
 '00165',
 '00249',
 '00709',
 '00127',
 '03240',
 '01154',
 '04679',
 '08945',
 '00337',
 '10982',
 '00034',
 '00846',
 '01925',
 '00893',
 '01857',
 '02507',
 '01256',
 '02336',
 '00996',
 '03425',
 '03113',
 '00256',
 '03296',
 '10408',
 '01008',
 '00014',
 '02601',
 '00211',
 '03007',
 '00093',
 '01094',
 '03030',
 '03084',
 '1881',
 '02859',
 '02589',
 '00066',
 '01176',
 '06021',
 '04667',
 '03092',
 '02739',
 '01858',
 '01765',
 '01352',
 '02222',
 '00083\u200b',
 '00226',
 '01511',
 '02384',
 '01974',
 '09038',
 '03394',
 '02843',
 '01689',
 '05719',
 '00610',
 '02790',
 '05101',
 '01949',
 '01609',
 '00327',
 '02674',
 '00381',
 '01274',
 '02578',
 '04793',
 '01847',
 '00076',
 '01840',
 '00209',
 '02211',
 '01046',
 '00473',
 '02367',
 '02664',
 '06030',
 '03167',
 '01819',
 '01150',
 '03454',
 '06185',
 '02457',
 '01935',
 '00639',
 '02284',
 '01862',
 '05115',
 '00493',
 '02669',
 '04192',
 '05262',
 '03376',
 '88432',
 '01577',
 '03299',
 '01424',
 '04633',
 '06015',
 '01433',
 '02010',
 '01044',
 '03057',
 '04073',
 '06036',
 '48',
 '05963',
 '03354',
 '02084',
 '00335',
 '08123',
 '03438',
 '01533',
 '05354',
 '01636',
 '00998',
 '00532',
 '05114',
 '01245',
 '00897',
 '01626',
 '00543',
 '00286',
 '00042',
 '01363',
 '05104',
 '02861',
 '01923',
 '01005',
 '00677',
 '01447',
 '02548',
 '00467',
 '01129',
 '00316',
 '00339',
 '02062',
 '03255',
 '00776',
 '01514',
 '02376',
 '09039',
 '00405',
 '02836',
 '02070',
 '02681',
 '02304',
 '03206',
 '08993',
 '00273',
 '00849',
 '03393',
 '00538',
 '00977',
 '03497',
 '00704',
 '02020',
 '02036',
 '01351',
 '02651',
 '02882',
 '01816',
 '05107',
 '01406',
 '01900',
 '00768',
 '00524',
 '01495',
 '00606',
 '01929',
 '00933',
 '00178',
 '02402',
 '00188',
 '01545',
 '00331',
 '01401',
 '04191',
 '00983',
 '03511',
 '01399',
 '01535',
 '06720',
 '03122',
 '02534',
 '05396',
 '02852',
 '00196',
 '00309',
 '01507',
 '01744',
 '01541',
 '01569',
 '00808',
 '00624',
 '01854',
 '00716',
 '01419',
 '01597',
 '01617',
 '00371',
 '01310',
 '02051',
 '00755',
 '00907',
 '00481',
 '08944',
 '01651',
 '01774',
 '02039',
 '01725',
 '03034',
 '87720',
 '00018',
 '08938',
 '01943',
 '00397',
 '04621',
 '02514',
 '00885',
 '01596',
 '02524',
 '01242',
 '00035',
 '02095',
 '00904',
 '02031',
 '05995',
 '00387',
 '09044',
 '02814',
 '00032',
 '03939',
 '03335',
 '00102',
 '04347',
 '00380',
 '00916',
 '01142',
 '00761',
 '06003',
 '00548',
 '10979',
 '02850',
 '01019',
 '000167',
 '01983',
 '01392',
 '02267',
 '03093',
 '0-1528',
 '06182',
 '11002',
 '01527',
 '02377',
 '03391',
 '06312',
 '01346',
 '00522',
 '05121',
 '00631',
 '02979',
 '00208',
 '00850',
 '00233',
 '02024',
 '03019',
 '00123',
 '00091',
 '00889',
 '05267',
 '11005',
 '00462',
 '01985',
 '01907',
 '00222',
 '01557',
 '03254',
 '04620',
 '09027',
 '04030',
 '00910',
 '11163',
 '00085',
 '00361',
 '06009',
 '01383',
 '04674',
 '01098',
 '00342',
 '00255',
 '01086',
 '00359',
 '00799',
 '00187',
 '03292',
 '03434',
 '02977',
 '03217',
 '00236',
 '01563',
 '02215',
 '04688',
 '08927',
 '00875',
 '02860',
 '04008',
 '03237',
 '10983',
 '00666',
 '01960',
 '02771',
 '05227',
 '01628',
 '02676',
 '04641',
 '01915',
 '01307',
 '01469',
 '02451',
 '01802',
 '04681',
 '10993',
 '03312',
 '01555',
 '01589',
 '11000',
 '02395',
 '02401',
 '01146',
 '01940',
 '02297',
 '01124',
 '03189',
 '0030',
 '02200',
 '01042',
 '01360',
 '02638',
 '08519',
 '01997',
 '00682',
 '03372',
 '08970',
 '04646',
 '00323',
 '01394',
 '02972',
 '01623',
 '01384',
 '03187',
 '03062',
 '00365',
 '02854',
 '06061',
 '00489',
 '00169',
 '00773',
 '00732',
 '002.5',
 '01295',
 '00652',
 '01980',
 '04687',
 '08989',
 '02056',
 '02643',
 '10991',
 '00504',
 '02110',
 '03527',
 '00547',
 '02777',
 '02802',
 '03061',
 '01345',
 '0034',
 '05123',
 '01998',
 '03200',
 '02345',
 '00071',
 '01460',
 '01189',
 '02765',
 '00203',
 '00418',
 '01885',
 '00200',
 '00945',
 '08942',
 '00201',
 '01416',
 '01579',
 '01632',
 '04802',
 '00835',
 '00582',
 '01699',
 '01939',
 '01278',
 '02612',
 '01817',
 '02052',
 '01613',
 '00749',
 '01466',
 '03487',
 '01431',
 '02355',
 '09001',
 '00070',
 '0012',
 '01955',
 '01804',
 '00477',
 '01582',
 '01325',
 '00118',
 '00024',
 '09002',
 '00753',
 '00308',
 '00367',
 '05266',
 '00057',
 '04624',
 '08245',
 '00404',
 '00214',
 '01917',
 '00955',
 '01422',
 '02735',
 '01810',
 '00312',
 '02819',
 '00231',
 '00936',
 '02008',
 '02366',
 '00501',
 '00957',
 '03008',
 '00221',
 '02925',
 '03207',
 '05232',
 '03533',
 '00619',
 '00229',
 '00735',
 '04693',
 '00240',
 '00168',
 '00662',
 '01190',
 '01823',
 '04011',
 '00964',
 '01576',
 '08921',
 '00307',
 '01303',
 '00186',
 '00464',
 '00277',
 '02254',
 '05189',
 '02588',
 '00646',
 '02268',
 '01715',
 '03614',
 '00132',
 '02161',
 '05973',
 '00438',
 '01480',
 '00390',
 '04696',
 '02848',
 '04074',
 '01258',
 '00987',
 '02792',
 '00748',
 '00098',
 '02029',
 '06723',
 '89',
 '02926',
 '05124',
 '01732',
 '05977',
 '02694',
 '00591',
 '00184',
 '01529',
 '03399',
 '05111',
 '10984',
 '00325',
 '00163',
 '00862',
 '00469',
 '00967',
 '02455',
 '01866',
 '00346',
 '06043',
 '02094',
 '08910',
 '02153',
 '01159',
 '02748',
 '02469',
 '01328',
 '01733',
 '01724',
 '00580',
 '01554',
 '00909',
 '05196',
 '00960',
 '01989',
 '00311',
 '00693',
 '00722',
 '01896',
 '00243',
 '00717',
 '01018',
 '01333',
 '01500',
 '196',
 '01612',
 '00285',
 '02196',
 '09017',
 '00322',
 '00541',
 '00555',
 '00635',
 '02905',
 '153',
 '03315',
 '00648',
 '02312',
 '00559',
 '02399',
 '02845',
 '03501',
 '00771',
 '01155',
 '00320',
 '01271',
 '01380',
 '06724',
 '01775',
 '03094',
 '05341',
 '01187',
 '00334',
 '01214',
 '03182',
 '05113',
 '01528',
 '00794',
 '01473',
 '00025',
 '00197',
 '01115',
 '00947',
 '00527',
 '05129',
 '03048',
 '00287',
 '00803',
 '00449',
 '05117',
 '01144',
 '02807',
 '00658',
 '00153',
 '05986',
 '00784',
 '01930',
 '01723',
 '08967',
 '02968',
 '01438',
 '01536',
 '01797',
 '00530',
 '01662',
 '01890',
 '00518',
 '00088',
 '02550',
 '09033',
 '00264',
 '00393',
 '00965',
 '00439',
 '00815',
 '02170',
 '01991',
 '04639',
 '01065',
 '01606',
 '00166',
 '02319',
 '00002',
 '04738',
 '09031',
 '00921',
 '00758',
 '00902',
 '01104',
 '01510',
 '03386',
 '01270',
 '03176',
 '06722',
 '134',
 '01680',
 '00839',
 '02841',
 '02335',
 '02341',
 '01676',
 '00780',
 '01165',
 '00789',
 '02701',
 '05958',
 '06020',
 '00877',
 '03325',
 '00419',
 '02001',
 '01193',
 '01879',
 '02072',
 '00250',
 '01347',
 '22222',
 '02526',
 '03100',
 '0014',
 '01326',
 '08069',
 '10506',
 '01806',
 '02124',
 '02030',
 '02155',
 '04623',
 '02068',
 '04730',
 '01524',
 '01668',
 '00954',
 '04622',
 '05993',
 '00552',
 '01796',
 '02784',
 '03273',
 '00675',
 '00470',
 '01237',
 '02212',
 '08976',
 '00581',
 '04004',
 '04800',
 '08981',
 '02378',
 '01731',
 '00931',
 '08940',
 '00892',
 '00708',
 '04690',
 '02071',
 '00832',
 '01078',
 '01575',
 '02405',
 '00274',
 '02067',
 '03503',
 '02517',
 '01769',
 '06019',
 '00433',
 '01354',
 '00333',
 '02869',
 '00558',
 '00258',
 '01213',
 '02770',
 '01435',
 '04673',
 '00691',
 '04634',
 '00336',
 '00959',
 '01574',
 '02584',
 '01758',
 '00805',
 '00720',
 '01550',
 '02647',
 '01100',
 '01904',
 '01738',
 '00112',
 '00417',
 '03356',
 '01331',
 '06062',
 '03507',
 '02631',
 '04087',
 '08978',
 '00734',
 '00589',
 '04644',
 '02103',
 '00900',
 '0018',
 '01755',
 '02668',
 '03954',
 '00006',
 '01093',
 '02536',
 '03483',
 '05718',
 '02754',
 '00090',
 '00884',
 '02613',
 '04631',
 '04655',
 '112',
 '01978',
 '00872',
 '01864',
 '05292',
 '05996',
 '02408',
 '00611',
 '01633',
 '01756',
 '02162',
 '03445',
 '01317',
 '02874',
 '10011',
 '01873',
 '00364',
 '00479',
 '00416',
 '02714',
 '00037',
 '03934',
 '01314',
 '01130',
 '00355',
 '02177',
 '01327',
 '00615',
 '02349',
 '02387',
 '05770',
 '00068',
 '02057',
 '01003',
 '05991',
 '01825',
 '02975',
 '01981',
 '00343',
 '05343',
 '00950',
 '04061',
 '09018',
 '05147',
 '08984',
 '05318',
 '05093',
 '01958',
 '05097',
 '04672',
 '01616',
 '02823',
 '01096',
 '00844',
 '00833',
 '00194',
 '05715',
 '01624',
 '00456',
 '01483',
 '02176',
 '01782',
 '00272',
 '08949',
 '01364',
 '03248',
 '04682',
 '01376',
 '00020',
 '01767',
 '02555',
 ...}

In [158]:
drop_data['PartitionKey'].replace({'218':'ไม่ระบุ',
                            '16':'ไม่ระบุ',
                            '124':'ไม่ระบุ',
                            '179':'ไม่ระบุ',
                            '1881':'ไม่ระบุ',
                            '00083\u200b':'ไม่ระบุ',
                            '48':'ไม่ระบุ',
                            '7140':'ไม่ระบุ',
                            '000167':'ไม่ระบุ',
                            '0-1528':'ไม่ระบุ',
                            '0030':'ไม่ระบุ',
                            '002.5':'ไม่ระบุ',
                            '0034':'ไม่ระบุ',
                            '0012':'ไม่ระบุ',
                            '7197':'ไม่ระบุ',
                            '89':'ไม่ระบุ',
                            '196':'ไม่ระบุ',
                            '153':'67241',
                            '134':'ไม่ระบุ',
                            '0014':'ไม่ระบุ',
                            '0018':'ไม่ระบุ',
                            '112':'ไม่ระบุ',
                            '241':'ไม่ระบุ',}, inplace=True)

/usr/local/lib/python3.7/dist-packages/pandas/core/generic.py:6619: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return self._update_inplace(result)

In [159]:
set(drop_data['PartitionKey'])

{'05994',
 '00632',
 '04626',
 '01437',
 '20044',
 '02624',
 '02919',
 '01261',
 '02763',
 '03362',
 '02730',
 '01948',
 '01439',
 '03552',
 '00131',
 '01064',
 '00779',
 '01926',
 '09040',
 '04014',
 '00266',
 '01712',
 '03932',
 '01232',
 '00253',
 '08914',
 '00332',
 '00592',
 '00546',
 '01920',
 '00001',
 '05223',
 '01583',
 '02672',
 '03383',
 '03472',
 '04753',
 '02686',
 '00021',
 '01172',
 '01362',
 '03980',
 '00458',
 '05259',
 '05342',
 '04680',
 '02752',
 '00567',
 '05831',
 '01696',
 '02997',
 '02484',
 '02639',
 '03311',
 '01047',
 '03378',
 '01322',
 '02749',
 '01603',
 '00573',
 '05209',
 '00860',
 '02580',
 '01716',
 '02370',
 '01106',
 '04736',
 '02989',
 '00901',
 '03112',
 '01961',
 '00206',
 '01812',
 '01355',
 '04137',
 '00661',
 '05280',
 '00710',
 '01061',
 '01128',
 '01629',
 '01849',
 '00017',
 '00843',
 '03056',
 '08962',
 '00267',
 '00586',
 '00484',
 '00986',
 '01041',
 '00183',
 '03826',
 '02992',
 '05961',
 '00426',
 '01736',
 '00549',
 '01250',
 '02824',
 '02066',
 '90470',
 '01252',
 '01452',
 '03509',
 '04187',
 '06262',
 '00074',
 '00150',
 '00461',
 '01350',
 '01737',
 '01123',
 '02470',
 '02803',
 '01444',
 '00798',
 '01373',
 '00036',
 '00593',
 '00087',
 '00806',
 '02485',
 '05119',
 '00072',
 '00519',
 '02063',
 '02561',
 '03433',
 '00117',
 '01999',
 '00795',
 '01179',
 '02610',
 '00752',
 '01482',
 '01215',
 '01671',
 '00298',
 '02856',
 '00507',
 '01464',
 '01491',
 '00796',
 '03158',
 '01851',
 '09012',
 '02727',
 '02272',
 '01226',
 '01655',
 '00294',
 '01196',
 '03291',
 '05099',
 '00299',
 '03408',
 '00899',
 '08254',
 '01402',
 '02483',
 '02900',
 '00247',
 '23416',
 '01162',
 '00542',
 '01996',
 '00023',
 '00149',
 '08995',
 '00284',
 '04253',
 '01607',
 '00281',
 '01403',
 '00165',
 '00249',
 '00709',
 '00127',
 '03240',
 '01154',
 '04679',
 '08945',
 '00337',
 '10982',
 '00034',
 '00846',
 '01925',
 '00893',
 '01857',
 '02507',
 '01256',
 '02336',
 '00996',
 '03425',
 '03113',
 '00256',
 '03296',
 '10408',
 '01008',
 '00014',
 '02601',
 '00211',
 '03007',
 '00093',
 '01094',
 '03030',
 '03084',
 '02859',
 '02589',
 '00066',
 '01176',
 '06021',
 '04667',
 '03092',
 '02739',
 '01858',
 '01765',
 '01352',
 '02222',
 '01511',
 '00226',
 '02384',
 '01974',
 '09038',
 '03394',
 '02843',
 '01689',
 '05719',
 '00610',
 '02790',
 '05101',
 '01949',
 '01609',
 '00327',
 '02674',
 '00381',
 '01274',
 '02578',
 '04793',
 '01847',
 '00076',
 '01840',
 '00209',
 '02211',
 '01046',
 '00473',
 '02367',
 '02664',
 '06030',
 '03167',
 '01819',
 '01150',
 '03454',
 '06185',
 '02457',
 '01935',
 '00639',
 '02284',
 '01862',
 '05115',
 '00493',
 '02669',
 '04192',
 '05262',
 '03376',
 '88432',
 '01577',
 '03299',
 '01424',
 '04633',
 '06015',
 '01433',
 '02010',
 '01044',
 '03057',
 '04073',
 '06036',
 '05963',
 '03354',
 '02084',
 '00335',
 '08123',
 '03438',
 '01533',
 '05354',
 '01636',
 '00998',
 '00532',
 '05114',
 '01245',
 '00897',
 '01626',
 '00543',
 '00286',
 '00042',
 '01363',
 '05104',
 '02861',
 '01923',
 '01005',
 '00677',
 '01447',
 '02548',
 '00467',
 '01129',
 '00316',
 '00339',
 '02062',
 '03255',
 '00776',
 '01514',
 '02376',
 '09039',
 '00405',
 '02836',
 '02070',
 '02681',
 '02304',
 '03206',
 '08993',
 '00273',
 '00849',
 '03393',
 '00538',
 '00977',
 '03497',
 '00704',
 '02020',
 '02036',
 '01351',
 '02651',
 '02882',
 '01816',
 '05107',
 '01406',
 '01900',
 '00768',
 '00524',
 '01495',
 '00606',
 '01929',
 '00933',
 '00178',
 '02402',
 '00188',
 '01545',
 '00331',
 '01401',
 '04191',
 '00983',
 '03511',
 '01399',
 '01535',
 '06720',
 '03122',
 '02534',
 '05396',
 '02852',
 '00196',
 '00309',
 '01507',
 '01744',
 '01541',
 '01569',
 '00808',
 '00624',
 '01854',
 '00716',
 '01419',
 '01597',
 '01617',
 '00371',
 '01310',
 '02051',
 '00755',
 '00907',
 '00481',
 '08944',
 '01651',
 '01774',
 '02039',
 '01725',
 '03034',
 '87720',
 '00018',
 '08938',
 '01943',
 '00397',
 '04621',
 '02514',
 '00885',
 '01596',
 '02524',
 '01242',
 '00035',
 '02095',
 '00904',
 '02031',
 '05995',
 '00387',
 '09044',
 '02814',
 '00032',
 '03939',
 '03335',
 '00102',
 '04347',
 '00380',
 '00916',
 '01142',
 '00761',
 '06003',
 '00548',
 '10979',
 '02850',
 '01019',
 '01983',
 '01392',
 '02267',
 '03093',
 '11002',
 '06182',
 '01527',
 '02377',
 '03391',
 '06312',
 '01346',
 '00522',
 '05121',
 '00631',
 '02979',
 '00208',
 '00850',
 '00233',
 '02024',
 '03019',
 '00123',
 '00091',
 '00889',
 '05267',
 '11005',
 '00462',
 '01985',
 '01907',
 '00222',
 '01557',
 '03254',
 '04620',
 '09027',
 '04030',
 '00910',
 '11163',
 '00085',
 '00361',
 '06009',
 '01383',
 '04674',
 '01098',
 '00342',
 '00255',
 '01086',
 '00359',
 '00799',
 '00187',
 '03292',
 '03434',
 '02977',
 '03217',
 '00236',
 '01563',
 '02215',
 '04688',
 '08927',
 '00875',
 '02860',
 '04008',
 '03237',
 '10983',
 '00666',
 '01960',
 '02771',
 '05227',
 '01628',
 '02676',
 '04641',
 '01915',
 '01307',
 '01469',
 '02451',
 '01802',
 '04681',
 '10993',
 '03312',
 '01555',
 '01589',
 '11000',
 '02395',
 '02401',
 '01146',
 '01940',
 '02297',
 '01124',
 '03189',
 '02200',
 '01042',
 '01360',
 '02638',
 '08519',
 '01997',
 '00682',
 '03372',
 '08970',
 '04646',
 '00323',
 '01394',
 '02972',
 '01623',
 '01384',
 '03187',
 '03062',
 '00365',
 '02854',
 '06061',
 '00489',
 '00169',
 '00773',
 '00732',
 '01295',
 '01980',
 '00652',
 '04687',
 '08989',
 '02056',
 '02643',
 '10991',
 '00504',
 '02110',
 '03527',
 '00547',
 '02777',
 '02802',
 '03061',
 '01345',
 '05123',
 '01998',
 '03200',
 '02345',
 '00071',
 '01460',
 '01189',
 '02765',
 '00203',
 '00418',
 '01885',
 '00200',
 '00945',
 '08942',
 '00201',
 '01416',
 '01579',
 '01632',
 '04802',
 '00835',
 '00582',
 '01699',
 '01939',
 '01278',
 '02612',
 '01817',
 '02052',
 '01613',
 '00749',
 '01466',
 '03487',
 '01431',
 '02355',
 '09001',
 '00070',
 '01955',
 '01804',
 '00477',
 '01582',
 '01325',
 '00118',
 '00024',
 '09002',
 '00753',
 '00308',
 '00367',
 '05266',
 '00057',
 '04624',
 '08245',
 '00404',
 '00214',
 '01917',
 '00955',
 '01422',
 '02735',
 '01810',
 '00312',
 '02819',
 '00231',
 '00936',
 '02008',
 '02366',
 '00501',
 '00957',
 '03008',
 '00221',
 '02925',
 '03207',
 '05232',
 '03533',
 '00619',
 '00229',
 '00735',
 '04693',
 '00240',
 '00168',
 '00662',
 '01190',
 '01823',
 '04011',
 '00964',
 '01576',
 '08921',
 '00307',
 '01303',
 '00186',
 '00464',
 '00277',
 '02254',
 '05189',
 '02588',
 '00646',
 '02268',
 '01715',
 '03614',
 '00132',
 '02161',
 '05973',
 '00438',
 '01480',
 '00390',
 '04696',
 '02848',
 '04074',
 '01258',
 '00987',
 '02792',
 '00748',
 '00098',
 '02029',
 '06723',
 '02926',
 '05124',
 '01732',
 '05977',
 '02694',
 '00591',
 '00184',
 '01529',
 '03399',
 '05111',
 '10984',
 '00325',
 '00163',
 '00862',
 '00469',
 '00967',
 '02455',
 '01866',
 '00346',
 '06043',
 '02094',
 '08910',
 '02153',
 '01159',
 '02748',
 '02469',
 '01328',
 '01733',
 '01724',
 '00580',
 '01554',
 '00909',
 '05196',
 '00960',
 '01989',
 '00311',
 '00693',
 '00722',
 '01896',
 '00243',
 '00717',
 '01018',
 '01333',
 '01500',
 '01612',
 '00285',
 '02196',
 '09017',
 '00322',
 '00541',
 '00555',
 '00635',
 '02905',
 '03315',
 '00648',
 '02312',
 '00559',
 '02399',
 '02845',
 '03501',
 '00771',
 '01155',
 '00320',
 '01271',
 '01380',
 '06724',
 '01775',
 '03094',
 '05341',
 '01187',
 '00334',
 '01214',
 '03182',
 '05113',
 '01528',
 '00794',
 '01473',
 '00025',
 '00197',
 '01115',
 '00947',
 '00527',
 '05129',
 '03048',
 '00287',
 '00803',
 '00449',
 '05117',
 '01144',
 '02807',
 '00658',
 '00153',
 '05986',
 '00784',
 '01930',
 '01723',
 '08967',
 '02968',
 '01438',
 '01536',
 '01797',
 '00530',
 '01662',
 '01890',
 '00518',
 '00088',
 '02550',
 '09033',
 '00264',
 '00393',
 '00965',
 '00439',
 '00815',
 '02170',
 '01991',
 '04639',
 '01065',
 '01606',
 '00166',
 '02319',
 '00002',
 '04738',
 '09031',
 '00921',
 '00758',
 '00902',
 '01104',
 '01510',
 '03386',
 '01270',
 '03176',
 '06722',
 '01680',
 '00839',
 '02841',
 '02335',
 '02341',
 '01676',
 '00780',
 '01165',
 '00789',
 '02701',
 '05958',
 '06020',
 '00877',
 '03325',
 '00419',
 '02001',
 '01193',
 '01879',
 '02072',
 '00250',
 '01347',
 '22222',
 '02526',
 '03100',
 '01326',
 '08069',
 '10506',
 '01806',
 '02124',
 '02030',
 '02155',
 '04623',
 '02068',
 '04730',
 '01524',
 '01668',
 '00954',
 '04622',
 '05993',
 '00552',
 '01796',
 '02784',
 '03273',
 '00675',
 '00470',
 '01237',
 '02212',
 '08976',
 '00581',
 '04004',
 '04800',
 '08981',
 '02378',
 '01731',
 '00931',
 '08940',
 '00892',
 '00708',
 '04690',
 '02071',
 '00832',
 '01078',
 '01575',
 '02405',
 '00274',
 '02067',
 '03503',
 '02517',
 '01769',
 '06019',
 '00433',
 '01354',
 '00333',
 '02869',
 '00558',
 '01213',
 '00258',
 '02770',
 '01435',
 '04673',
 '00691',
 '04634',
 '00336',
 '00959',
 '01574',
 '02584',
 '01758',
 '00805',
 '00720',
 '01550',
 '02647',
 '01100',
 '01904',
 '01738',
 '00112',
 '00417',
 '03356',
 '01331',
 '06062',
 '03507',
 '02631',
 '04087',
 '08978',
 '00734',
 '00589',
 '04644',
 '02103',
 '00900',
 '01755',
 '02668',
 '03954',
 '00006',
 '01093',
 '02536',
 '03483',
 '05718',
 '02754',
 '00090',
 '00884',
 '02613',
 '04631',
 '04655',
 '01978',
 '00872',
 '01864',
 '05292',
 '05996',
 '02408',
 '00611',
 '01633',
 '01756',
 '02162',
 '03445',
 '01317',
 '02874',
 '10011',
 '01873',
 '00364',
 '00479',
 '00416',
 '02714',
 '00037',
 '03934',
 '01314',
 '01130',
 '00355',
 '02177',
 '01327',
 '00615',
 '02349',
 '02387',
 '05770',
 '00068',
 '02057',
 '01003',
 '05991',
 '01825',
 '02975',
 '01981',
 '00343',
 '05343',
 '00950',
 '04061',
 '09018',
 '05147',
 '08984',
 '05318',
 '05093',
 '01958',
 '05097',
 '04672',
 '01616',
 '02823',
 '01096',
 '00844',
 '00833',
 '00194',
 '05715',
 '01624',
 '00456',
 '01483',
 '02176',
 '01782',
 '00272',
 '08949',
 '01364',
 '03248',
 '04682',
 '01376',
 '00020',
 '01767',
 '02555',
 '03321',
 '03398',
 '08900',
 '02197',
 '08985',
 '02713',
 '00869',
 '01964',
 '01389',
 '01870',
 '00239',
 '05724',
 '00170',
 '01184',
 '02878',
 '00793',
 '02832',
 '02265',
 '01547',
 '02398',
 ...}